# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# Copyright (c) 2001, Dr Martin Porter,
# Copyright (c) 2002, Richard Boulton.
# All rights reserved.

include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - prefer_final_locals
    - sort_pub_dependencies
    - always_put_required_named_parameters_first
    - public_member_api_docs
    - type_annotate_public_apis

analyzer:
  exclude: 
    # - test/vocabulary.dart
  language:
    # strict-casts: true
    # strict-raw-types: true    
