# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

name: text_analysis
description: Text analyzer that tokenize text, compute readibility scores for a document and evaluate similarity of terms.
version: 0.13.0
repository: https://github.com/GM-Consult-Pty-Ltd/text_analysis
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/text_analysis/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.16.0
  porter_2_stemmer: ^1.0.0

dev_dependencies:
  gmconsult_dev: ^0.0.2
  lints: ^2.0.0
  test: ^1.21.1
