// BSD 3-Clause License
// Copyright ©2022, GM Consult Pty Ltd
// All rights reserved

part of 'english.dart';

/// Constants used by the [English] text analyzer.
abstract class _EnglishConstants {
  //

  /// The default lemmatizer returns the [term] unchanged.
  static String kLemmatizer(String term) => term;

  /// The default stemmer returns the [term] unchanged.
  static String kStemmer(String term) => term.stemPorter2();

  /// A collection of stop-words excluded from tokenization.
  static const kStopWords = {
    'a',
    'abaft',
    'abafter',
    'abaftest',
    'about',
    'abouter',
    'aboutest',
    'abov',
    'above',
    'abover',
    'abovest',
    'accord',
    'accordingly',
    'across',
    'aer',
    'aest',
    'afor',
    'afore',
    'after',
    'afterer',
    'afterest',
    'afterward',
    'afterwards',
    'again',
    'against',
    'aid',
    'ain',
    'albeit',
    'all',
    'aller',
    'allest',
    'alls',
    'allyou',
    'almost',
    'along',
    'alongsid',
    'alongside',
    'alreadi',
    'already',
    'also',
    'although',
    'alway',
    'always',
    'am',
    'amid',
    'amidst',
    'among',
    'amongst',
    'an',
    'and',
    'andor',
    'anear',
    'anent',
    'ani',
    'anoth',
    'another',
    'any',
    'anybodi',
    'anybody',
    'anyhow',
    'anyon',
    'anyone',
    'anyth',
    'anything',
    'anywher',
    'anywhere',
    'apart',
    'aparter',
    'apartest',
    'appear',
    'appeared',
    'appearing',
    'appears',
    'appropri',
    'appropriat',
    'appropriate',
    'appropriated',
    'appropriater',
    'appropriates',
    'appropriatest',
    'appropriating',
    'are',
    'ares',
    'around',
    'as',
    'ase',
    'ases',
    'asid',
    'aside',
    'asides',
    'aslant',
    'astraddl',
    'astraddle',
    'astraddler',
    'astraddlest',
    'astrid',
    'astride',
    'astrider',
    'astridest',
    'at',
    'athwart',
    'atop',
    'atween',
    'aught',
    'aughts',
    'avail',
    'availabl',
    'available',
    'availabler',
    'availablest',
    'aw',
    'awfully',
    'b',
    'be',
    'becam',
    'became',
    'becaus',
    'because',
    'becom',
    'become',
    'becomes',
    'becoming',
    'becominger',
    'becomingest',
    'becomings',
    'been',
    'befor',
    'before',
    'beforehand',
    'beforehander',
    'beforehandest',
    'behind',
    'behinds',
    'being',
    'below',
    'beneath',
    'besid',
    'beside',
    'besides',
    'better',
    'bettered',
    'bettering',
    'betters',
    'between',
    'betwixt',
    'beyond',
    'bist',
    'both',
    'but',
    'buts',
    'by',
    'byandbi',
    'byandby',
    'by-and-by',
    'c',
    'can',
    'cannot',
    'canst',
    'cant',
    'canted',
    'cantest',
    'canting',
    'cants',
    'case',
    'cer',
    'certain',
    'certainer',
    'certainest',
    'cest',
    'chez',
    'circa',
    'co',
    'comeon',
    'come-on',
    'comeons',
    'come-ons',
    'concern',
    'concerning',
    'concerninger',
    'concerningest',
    'consequ',
    'consequently',
    'consid',
    'considering',
    'could',
    'couldst',
    'cum',
    'd',
    'dday',
    'ddays',
    'describ',
    'describe',
    'described',
    'describes',
    'describing',
    'despit',
    'despite',
    'despited',
    'despites',
    'despiting',
    'did',
    'differ',
    'different',
    'differenter',
    'differentest',
    'do',
    'doe',
    'does',
    'doing',
    'doings',
    'don',
    'done',
    'doner',
    'dones',
    'donest',
    'dos',
    'dost',
    'doth',
    'down',
    'downs',
    'downward',
    'downwarder',
    'downwardest',
    'downwards',
    'dure',
    'during',
    'e',
    'each',
    'eg',
    'eight',
    'either',
    'els',
    'else',
    'elsewher',
    'elsewhere',
    'enough',
    'ere',
    'et',
    'etc',
    'even',
    'evened',
    'evenest',
    'evens',
    'evenser',
    'evensest',
    'event',
    'ever',
    'everi',
    'every',
    'everybodi',
    'everybody',
    'everyon',
    'everyone',
    'everyth',
    'everything',
    'everywher',
    'everywhere',
    'ex',
    'except',
    'excepted',
    'excepting',
    'excepts',
    'exe',
    'exes',
    'f',
    'fact',
    'facts',
    'fail',
    'failing',
    'failings',
    'few',
    'fewer',
    'fewest',
    'figupon',
    'figuponed',
    'figuponing',
    'figupons',
    'five',
    'follow',
    'following',
    'followthrough',
    'for',
    'forbi',
    'forby',
    'forbye',
    'fore',
    'forer',
    'fores',
    'forev',
    'forever',
    'former',
    'formerer',
    'formerest',
    'formerly',
    'formers',
    'fornenst',
    'forwhi',
    'forwhy',
    'four',
    'fourscor',
    'fourscore',
    'frae',
    'from',
    'fs',
    'further',
    'furthered',
    'furtherer',
    'furtherest',
    'furthering',
    'furthermor',
    'furthermore',
    'furthers',
    'g',
    'get',
    'gets',
    'getting',
    'go',
    'gone',
    'good',
    'got',
    'gotta',
    'gotten',
    'h',
    'had',
    'hadst',
    'hae',
    'hard',
    'hardly',
    'has',
    'hast',
    'hath',
    'have',
    'haves',
    'having',
    'he',
    'henc',
    'hence',
    'her',
    'here',
    'hereaft',
    'hereafter',
    'hereafters',
    'herebi',
    'hereby',
    'herein',
    'hereupon',
    'hers',
    'herself',
    'him',
    'himself',
    'his',
    'hither',
    'hitherer',
    'hitherest',
    'hoo',
    'hoos',
    'how',
    'howbeit',
    'howdoyoudo',
    'how-do-you-do',
    'howev',
    'however',
    'huh',
    'humph',
    'i',
    'idem',
    'idemer',
    'idemest',
    'ie',
    'if',
    'ifs',
    'immedi',
    'immediat',
    'immediate',
    'immediately',
    'immediater',
    'immediatest',
    'in',
    'inasmuch',
    'inc',
    'includ',
    'including',
    'inde',
    'indeed',
    'indic',
    'indicate',
    'indicated',
    'indicates',
    'indicating',
    'info',
    'inform',
    'information',
    'insofar',
    'instead',
    'into',
    'inward',
    'inwarder',
    'inwardest',
    'inwards',
    'is',
    'it',
    'its',
    'itself',
    'j',
    'just',
    'k',
    'l',
    'last',
    'latter',
    'latterer',
    'latterest',
    'latterly',
    'latters',
    'layabout',
    'layabouts',
    'least',
    'less',
    'lest',
    'like',
    'littl',
    'little',
    'long',
    'lot',
    'lots',
    'lotted',
    'lotting',
    'm',
    'main',
    'make',
    'mani',
    'many',
    'mauger',
    'maugr',
    'maugre',
    'mayest',
    'me',
    'meanwhil',
    'meanwhile',
    'meanwhiles',
    'midst',
    'midsts',
    'might',
    'mights',
    'mine',
    'more',
    'moreov',
    'moreover',
    'most',
    'mostly',
    'much',
    'mucher',
    'muchest',
    'must',
    'musth',
    'musths',
    'musts',
    'my',
    'myself',
    'n',
    'natheless',
    'nathless',
    'naught',
    'near',
    'neath',
    'neaths',
    'necessari',
    'necessarier',
    'necessariest',
    'necessary',
    'neither',
    'neth',
    'nethe',
    'nethermost',
    'never',
    'nevertheless',
    'next',
    'nigh',
    'nigher',
    'nighest',
    'nine',
    'no',
    'nobodi',
    'nobodies',
    'nobody',
    'noe',
    'noes',
    'none',
    'noon',
    'no-on',
    'noone',
    'no-one',
    'nor',
    'nos',
    'not',
    'noth',
    'nothing',
    'nothings',
    'notwithstand',
    'notwithstanding',
    'nought',
    'now',
    'nowher',
    'nowhere',
    'nowheres',
    'o',
    'of',
    'off',
    'offest',
    'offs',
    'often',
    'oftener',
    'oftenest',
    'oh',
    'on',
    'onc',
    'once',
    'one',
    'oneself',
    'onest',
    'only',
    'ons',
    'onto',
    'or',
    'order',
    'orer',
    'orest',
    'other',
    'others',
    'otherwis',
    'otherwise',
    'otherwiser',
    'otherwisest',
    'ought',
    'oughts',
    'our',
    'ours',
    'ourself',
    'ourselv',
    'ourselves',
    'out',
    'outed',
    'outest',
    'outs',
    'outsid',
    'outside',
    'outwith',
    'over',
    'overal',
    'overall',
    'overaller',
    'overallest',
    'overalls',
    'overs',
    'own',
    'owned',
    'owning',
    'owns',
    'owt',
    'p',
    'particular',
    'particularer',
    'particularest',
    'particularly',
    'particulars',
    'past',
    'per',
    'perhap',
    'perhaps',
    'plaintiff',
    'pleas',
    'please',
    'pleased',
    'pleases',
    'plenti',
    'plenties',
    'plenty',
    'plus',
    'pro',
    'probabl',
    'probably',
    'provid',
    'provide',
    'provided',
    'provides',
    'providing',
    'q',
    'qua',
    'que',
    'quit',
    'quite',
    'r',
    'rath',
    'rathe',
    'rather',
    'rathest',
    're',
    'realli',
    'really',
    'regard',
    'regarding',
    'relat',
    'relate',
    'related',
    'relatively',
    'res',
    'respect',
    'respecting',
    'respectively',
    's',
    'said',
    'saider',
    'saidest',
    'same',
    'samer',
    'sames',
    'samest',
    'san',
    'sans',
    'sanserif',
    'sanserifs',
    'sanses',
    'save',
    'saved',
    'sayid',
    'sayyid',
    'seem',
    'seemed',
    'seeming',
    'seeminger',
    'seemingest',
    'seemingly',
    'seemings',
    'seems',
    'send',
    'sent',
    'senza',
    'serious',
    'seriouser',
    'seriousest',
    'seven',
    'sever',
    'several',
    'severaler',
    'severalest',
    'shall',
    'shalled',
    'shalling',
    'shalls',
    'she',
    'should',
    'shoulded',
    'shoulding',
    'shoulds',
    'sinc',
    'since',
    'sine',
    'sines',
    'sith',
    'six',
    'so',
    'sobeit',
    'soer',
    'soest',
    'some',
    'somebodi',
    'somebody',
    'somehow',
    'someon',
    'someone',
    'someth',
    'something',
    'sometim',
    'sometime',
    'sometimer',
    'sometimes',
    'sometimest',
    'somewhat',
    'somewher',
    'somewhere',
    'soon',
    'stop',
    'stopped',
    'such',
    'suchlik',
    'suchlike',
    'suffici',
    'sufficient',
    'summat',
    'sup',
    'supped',
    'supping',
    'suppos',
    'supposing',
    'sups',
    'syn',
    'syne',
    't',
    'ten',
    'than',
    'that',
    'the',
    'thee',
    'their',
    'theirs',
    'theirself',
    'theirselv',
    'theirselves',
    'them',
    'themself',
    'themselv',
    'themselves',
    'then',
    'thenc',
    'thence',
    'thener',
    'thenest',
    'there',
    'thereaft',
    'thereafter',
    'therebi',
    'thereby',
    'therefor',
    'therefore',
    'therein',
    'therer',
    'therest',
    'thereupon',
    'these',
    'they',
    'thi',
    'thine',
    'thing',
    'things',
    'this',
    'thise',
    'thises',
    'thorough',
    'thorougher',
    'thoroughest',
    'thoroughly',
    'those',
    'thou',
    'though',
    'thous',
    'thouses',
    'three',
    'thro',
    'through',
    'througher',
    'throughest',
    'throughout',
    'thru',
    'thruer',
    'thruest',
    'thus',
    'thy',
    'thyself',
    'till',
    'tilled',
    'tilling',
    'tills',
    'time',
    'to',
    'togeth',
    'together',
    'too',
    'toward',
    'towarder',
    'towardest',
    'towards',
    'two',
    'u',
    'umpteen',
    'under',
    'underneath',
    'unless',
    'unlik',
    'unlike',
    'unliker',
    'unlikest',
    'until',
    'unto',
    'up',
    'upon',
    'uponed',
    'uponing',
    'upons',
    'upped',
    'upping',
    'ups',
    'us',
    'use',
    'used',
    'usedest',
    'usernam',
    'username',
    'usual',
    'usually',
    'v',
    'various',
    'variouser',
    'variousest',
    'veri',
    'verier',
    'veriest',
    'versus',
    'very',
    'via',
    'vis-a-vi',
    'vis-a-vis',
    'vis-a-viser',
    'vis-a-visest',
    'viz',
    'vs',
    'w',
    'was',
    'wast',
    'we',
    'were',
    'wert',
    'what',
    'whatev',
    'whatever',
    'whateverer',
    'whateverest',
    'whatnot',
    'whatsoev',
    'whatsoever',
    'whatsoeverer',
    'whatsoeverest',
    'wheen',
    'when',
    'whena',
    'whenas',
    'whenc',
    'whence',
    'whencesoev',
    'whencesoever',
    'whenev',
    'whenever',
    'whensoev',
    'whensoever',
    'where',
    'wherea',
    'whereaft',
    'whereafter',
    'whereas',
    'wherebi',
    'whereby',
    'wherefrom',
    'wherein',
    'whereinto',
    'whereof',
    'whereon',
    'wheresoev',
    'wheresoever',
    'whereto',
    'whereunto',
    'whereupon',
    'wherev',
    'wherever',
    'wherewith',
    'wherewithal',
    'whether',
    'whi',
    'which',
    'whichev',
    'whichever',
    'whichsoev',
    'whichsoever',
    'while',
    'whiles',
    'whilst',
    'whither',
    'whithersoev',
    'whithersoever',
    'who',
    'whoever',
    'whom',
    'whomev',
    'whomever',
    'whomso',
    'whomsoev',
    'whomsoever',
    'whose',
    'whosesoev',
    'whosesoever',
    'whosev',
    'whosever',
    'whoso',
    'whosoev',
    'whosoever',
    'why',
    'will',
    'with',
    'withal',
    'within',
    'without',
    'would',
    'woulded',
    'woulding',
    'woulds',
    'x',
    'y',
    'ye',
    'yet',
    'yon',
    'yond',
    'yonder',
    'you',
    'your',
    'yours',
    'yourself',
    'yourselv',
    'yourselves',
    'z',
    'zillion',
  };

  /// A list of English abbreviations.
  static const kAbbreviations = {
    'a.': 'ante',
    'a.d.': 'Anno Domini',
    'A.D.': 'Anno Domini',
    'a.v.': 'Authorized Version',
    'A.V.': 'Authorized Version',
    'abbrev.': 'abbreviation',
    'Abbrev.': 'abbreviations',
    'abd.': 'Aberdeen',
    'Abd.': 'Aberdeen',
    'aberd.': 'Aberdeen',
    'Aberd.': 'Aberdeen',
    'aberdeensh.': 'Aberdeenshire',
    'Aberdeensh.': 'Aberdeenshire',
    'abl.': 'ablative',
    'abol.': 'abolition',
    'Abol.': 'abolition',
    'aborig.': 'aboriginal',
    'Aborig.': 'aboriginal',
    'abp.': 'archbishop',
    'Abp.': 'archbishop',
    'abr.': 'abridged',
    'Abr.': 'abridged',
    'abridg.': 'abridged',
    'Abridg.': 'abridged',
    'abridgem.': 'abridgement',
    'Abridgem.': 'abridgement',
    'absol.': 'absolute',
    'Absol.': 'absolute',
    'abst.': 'abstracts',
    'Abst.': 'abstracts',
    'abstr.': 'abstract',
    'Abstr.': 'abstracts',
    'acad.': 'academia, academy, academical',
    'Acad.': 'academia, academy, academical',
    'acc.': 'accounts',
    'Acc.': 'accounts',
    'accept.': 'acceptance',
    'Accept.': 'acceptance',
    'accomm.': 'accommodation',
    'Accomm.': 'accommodation',
    'accompl.': 'accomplished',
    'Accompl.': 'accomplished',
    'accs.': 'accounts',
    'Accs.': 'accounts',
    'acct.': 'account',
    'Acct.': 'account',
    'accts.': 'accounts',
    'Accts.': 'accounts',
    'accus.': 'accusative',
    'achievem.': 'achievement',
    'Achievem.': 'achievement',
    'ad.': 'adaptation of',
    'add.': 'addendum, addenda',
    'Add.': 'addendum, addenda',
    'addit.': 'additions',
    'Addit.': 'additions',
    'addr.': 'address',
    'Addr.': 'address',
    'adj.': 'adjective, adjectival',
    'adj. phr.': 'adjectival phrase',
    'adjs.': 'adjectives',
    'adm.': 'admiral, admiralty',
    'Adm.': 'admiral, admiralty',
    'admin.': 'administration, administrative',
    'Admin.': 'administration, administrative',
    'admir.': 'admiralty',
    'Admir.': 'admiralty',
    'admon.': 'admonition',
    'Admon.': 'admonition',
    'admonit.': 'admonition',
    'Admonit.': 'admonition',
    'adv.': 'adverb, adverbially',
    'Adv.': 'advices, advances, adventures',
    'advancem.': 'advancements',
    'Advancem.': 'advancements',
    'advb.': 'adverb, adverbially',
    'advert.': 'advertisement',
    'Advert.': 'advertisement',
    'advoc.': 'advocate',
    'Advoc.': 'advocate',
    'advs.': 'adverbs',
    'advt.': 'advertisement',
    'Advt.': 'advertisement',
    'advts.': 'advertisements',
    'Advts.': 'advertisements',
    'aerodynam.': 'aerodynamics',
    'Aerodynam.': 'aerodynamics',
    'aeronaut.': 'aeronautics, aeronautical',
    'Aeronaut.': 'aeronautics, aeronautical',
    'aff.': 'affairs',
    'Aff.': 'affairs',
    'affect.': 'affecting, affections',
    'Affect.': 'affecting, affections',
    'afr.': 'African',
    'Afr.': 'African',
    'agric.': 'agriculture, agricultural',
    'Agric.': 'agriculture, agricultural',
    'agst.': 'against',
    'alch.': 'alchemy',
    'Alch.': 'alchemy',
    'alg.': 'algebra',
    'Alg.': 'algebra',
    'alleg.': 'allegiance',
    'Alleg.': 'allegiance',
    'allit.': 'alliterative',
    'Allit.': 'alliterative',
    'alm.': 'almanac',
    'Alm.': 'almanac',
    'alph.': 'alphabet, alphabetical',
    'Alph.': 'alphabet, alphabetical',
    'alt.': 'alteration',
    'amer.': 'America, American',
    'Amer.': 'America, American',
    'anal.': 'analysis',
    'Anal.': 'analysis',
    'analyt.': 'analytical',
    'Analyt.': 'analytical',
    'anat.': 'anatomy, anatomical',
    'Anat.': 'anatomy, anatomical',
    'anc.': 'ancient',
    'Anc.': 'ancient',
    'anecd.': 'anecdotes',
    'Anecd.': 'anecdotes',
    'ang.': 'Anglian',
    'Ang.': 'Anglian',
    'angl.': 'Anglian',
    'Angl.': 'Anglian',
    'anglo-ind.': 'Anglo-Indian',
    'Anglo-Ind.': 'Anglo-Indian',
    'anim.': 'animals',
    'Anim.': 'animals',
    'ann.': 'annals, annual',
    'Ann.': 'annals, annual',
    'anniv.': 'anniversary',
    'Anniv.': 'anniversary',
    'annot.': 'annotation',
    'Annot.': 'annotation',
    'anon.': 'Anonymous',
    'Anon.': 'Anonymous',
    'answ.': 'answer',
    'Answ.': 'answer',
    'ant.': 'antiquities',
    'Ant.': 'antiquities',
    'anthrop.': 'anthropology',
    'Anthrop.': 'anthropology',
    'anthropol.': 'anthropology, anthropological',
    'Anthropol.': 'anthropology, anthropological',
    'antiq.': 'antiquity, antiquities',
    'Antiq.': 'antiquity, antiquities',
    'aphet.': 'aphetic, aphetized',
    'apoc.': 'apocalyptical',
    'Apoc.': 'apocalyptical',
    'apol.': 'apology, apologies',
    'Apol.': 'apology, apologies',
    'app.': 'apparently',
    'App.': 'appendix',
    'appl.': 'applied',
    'Appl.': 'applied',
    'applic.': 'applications',
    'Applic.': 'applications',
    'appos.': 'appositively',
    'apr.': 'April',
    'Apr.': 'April',
    'arab.': 'Arabic',
    'Arab.': 'Arabic',
    'arb.': 'Arber',
    'Arb.': 'Arber',
    'arch.': 'archaic',
    'Arch.': 'architecture, archives',
    'archaeol.': 'archaeology, archaeological',
    'Archaeol.': 'archaeology, archaeological',
    'archipel.': 'archipelago',
    'Archipel.': 'archipelago',
    'archit.': 'architecture, architectural',
    'Archit.': 'architecture, architectural',
    'argt.': 'argument',
    'Argt.': 'argument',
    'arith.': 'arithmetic',
    'Arith.': 'arithmetic',
    'arithm.': 'arithmetic, arithmetical',
    'Arithm.': 'arithmetic, arithmetical',
    'arrangem.': 'arrangement',
    'Arrangem.': 'arrangement',
    'art.': 'article',
    'artic.': 'articulation',
    'Artic.': 'articulation',
    'artific.': 'artificial',
    'Artific.': 'artificial',
    'artill.': 'artillery',
    'Artill.': 'artillery',
    'ashm.': 'Ashmole',
    'Ashm.': 'Ashmole',
    'assemb.': 'assembly, assemblies',
    'Assemb.': 'assembly, assemblies',
    'assoc.': 'association',
    'Assoc.': 'association',
    'assoc. football': 'Association Football',
    'Assoc. Football': 'Association Football',
    'assyriol.': 'Assyriology',
    'Assyriol.': 'Assyriology',
    'astr.': 'astronomy',
    'Astr.': 'astronomy',
    'astrol.': 'astrology',
    'Astrol.': 'astrology',
    'astron.': 'astronomy, astronomical',
    'Astron.': 'astronomy, astronomical',
    'astronaut.': 'astronautics, astronautical',
    'Astronaut.': 'astronautics, astronautical',
    'att.': 'Attic',
    'Att.': 'Attic',
    'attrib.': 'attributes',
    'Attrib.': 'attributes',
    'aug.': 'August',
    'Aug.': 'August',
    'austral.': 'Australian',
    'Austral.': 'Australian',
    'auth.': 'authors',
    'Auth.': 'authors',
    'autobiog.': 'autobiography',
    'Autobiog.': 'autobiography',
    'autobiogr.': 'autobiography, autobiographical',
    'Autobiogr.': 'autobiography, autobiographical',
    'ayrsh.': 'Ayrshire',
    'Ayrsh.': 'Ayrshire',
    'b.c.': 'Before Christ, British Columbia',
    'B.C.': 'Before Christ, British Columbia',
    'bacteriol.': 'bacteriology, bacteriological',
    'Bacteriol.': 'bacteriology, bacteriological',
    'bedford.': 'Bedfordshire',
    'Bedford.': 'Bedfordshire',
    'bedfordsh.': 'Bedfordshire',
    'Bedfordsh.': 'Bedfordshire',
    'bef.': 'before',
    'bel & dr.': 'Bel and the Dragon',
    'Bel & Dr.': 'Bel and the Dragon',
    'belg.': 'Belgian',
    'Belg.': 'Belgian',
    'berks.': 'Berkshire',
    'Berks.': 'Berkshire',
    'berksh.': 'Berkshire',
    'Berksh.': 'Berkshire',
    'berw.': 'Berwickshire',
    'Berw.': 'Berwickshire',
    'berwicksh.': 'Berwickshire',
    'Berwicksh.': 'Berwickshire',
    'betw.': 'between',
    'bibliogr.': 'bibliography',
    'Bibliogr.': 'bibliography',
    'biochem.': 'biochemistry, biochemical',
    'Biochem.': 'biochemistry, biochemical',
    'biog.': 'biography',
    'Biog.': 'biography',
    'biogr.': 'biography, biographical',
    'Biogr.': 'biography, biographical',
    'biol.': 'biology, biological',
    'Biol.': 'biology, biological',
    'bk.': 'book',
    'Bk.': 'book',
    'bks.': 'books',
    'Bks.': 'books',
    'bnc': 'British National Corpus',
    'BNC': 'British National Corpus',
    'bord.': 'border',
    'Bord.': 'border',
    'bot.': 'botany, botanical',
    'Bot.': 'botany, botanical',
    'bp.': 'Bishop',
    'Bp.': 'Bishop',
    'braz.': 'Brazilian',
    'Braz.': 'Brazilian',
    'brit.': 'Britain, British',
    'Brit.': 'Britain, British',
    'bucks.': 'Buckinghamshire',
    'Bucks.': 'Buckinghamshire',
    'build.': 'building',
    'Build.': 'building',
    'bull.': 'bulletin',
    'Bull.': 'bulletin',
    'bur.': 'bureau',
    'Bur.': 'bureau',
    'c': 'circa',
    'c.': 'century',
    'C.': 'county, counties',
    'cal.': 'calendar',
    'Cal.': 'calendar',
    'calc.': 'calculus',
    'Calc.': 'calculus',
    'calend.': 'calendar',
    'Calend.': 'calendar',
    'calif.': 'California',
    'Calif.': 'California',
    'calligr.': 'calligraphy',
    'Calligr.': 'calligraphy',
    'camb.': 'Cambridge',
    'Camb.': 'Cambridge',
    'cambr.': 'Cambridge',
    'Cambr.': 'Cambridge',
    'campanol.': 'campanology',
    'Campanol.': 'campanology',
    'canad.': 'Canadian',
    'Canad.': 'Canadian',
    'canterb.': 'Canterbury',
    'Canterb.': 'Canterbury',
    'capt.': 'captain',
    'Capt.': 'captain',
    'cartogr.': 'cartography, cartographical',
    'Cartogr.': 'cartography, cartographical',
    'catal.': 'catalogue',
    'Catal.': 'catalogue',
    'catech.': 'catechism',
    'Catech.': 'catechism',
    'cath.': 'Catholic',
    'Cath.': 'Catholic',
    'cent.': 'century',
    'Cent.': 'central, Century',
    'ceram.': 'ceramics',
    'Ceram.': 'ceramics',
    'cert.': 'certificate',
    'Cert.': 'certificate',
    'certif.': 'certificate',
    'Certif.': 'certificate',
    'cf.': 'confer, compare',
    'ch.': 'Church',
    'Ch.': 'Church',
    'ch. hist.': 'Church history',
    'Ch. Hist.': 'Church history',
    'chamb.': 'chamber',
    'Chamb.': 'chamber',
    'char.': 'character',
    'Char.': 'character',
    'charac.': 'character',
    'Charac.': 'character',
    'chas.': 'Charles',
    'Chas.': 'Charles',
    'chem.': 'chemistry, chemical',
    'Chem.': 'chemistry, chemical',
    'chem. engin.': 'chemical engineering',
    'Chem. Engin.': 'chemical engineering',
    'chesh.': 'Cheshire',
    'Chesh.': 'Cheshire',
    'chr.': 'Chronicles, Christian',
    'Chr.': 'Chronicles, Christian',
    'chron.': 'Chronicles, chronology, chronicle',
    'Chron.': 'Chronicles, chronology, chronicle',
    'chronol.': 'chronology',
    'Chronol.': 'chronology',
    'chrons.': 'chronicles',
    'Chrons.': 'chronicles',
    'cinematogr.': 'cinematography, cinematographical',
    'Cinematogr.': 'cinematography, cinematographical',
    'circ.': 'circle',
    'Circ.': 'circle',
    'civ. law': 'civil law',
    'Civ. Law': 'civil law',
    'civil engin.': 'civil engineering',
    'Civil Engin.': 'civil engineering',
    'cl.': 'clause',
    'Cl.': 'club',
    'class.': 'classical',
    'Class.': 'classical',
    'class. antiq.': 'classical antiquities',
    'Class. Antiq.': 'classical antiquities',
    'classif.': 'classification',
    'Classif.': 'classification',
    'climatol.': 'climatology',
    'Climatol.': 'climatology',
    'clin.': 'clinical',
    'Clin.': 'clinical',
    'cogn. w.': 'cognate with',
    'col.': 'Colossians, colonel',
    'Col.': 'Colossians, colonel',
    'coll.': 'collected, collection, college',
    'Coll.': 'collected, collection, college',
    'collect.': 'collection',
    'Collect.': 'collection',
    'colloq.': 'colloquially',
    'Colloq.': 'colloquies',
    'coloss.': 'Colossians',
    'Coloss.': 'Colossians',
    'com.': 'commission, common',
    'Com.': 'commission, common',
    'comb.': 'combinations',
    'Comb.': 'combinations',
    'comb. form': 'combining form',
    'combs.': 'combinations',
    'Combs.': 'combinations',
    'comm.': 'committee, commission',
    'Comm.': 'committee, commission',
    'comm. law': 'commercial law',
    'Comm. Law': 'commercial law',
    'commandm.': 'commandment',
    'Commandm.': 'commandment',
    'commend.': 'commendation',
    'Commend.': 'commendation',
    'commerc.': 'commercial',
    'Commerc.': 'commercial',
    'commiss.': 'commission',
    'Commiss.': 'commission',
    'commonw.': 'commonwealth',
    'Commonw.': 'commonwealth',
    'communic.': 'communications',
    'Communic.': 'communications',
    'comp.': 'companion, company',
    'Comp.': 'companion, company',
    'comp. anat.': 'comparative anatomy',
    'Comp. Anat.': 'comparative anatomy',
    'compan.': 'companions',
    'Compan.': 'companions',
    'compar.': 'comparative',
    'Compar.': 'comparative',
    'compend.': 'compendium, compendious',
    'Compend.': 'compendium, compendious',
    'compl.': 'complement',
    'Compl.': 'complete',
    'compos.': 'composition',
    'Compos.': 'composition',
    'conc.': 'concerning',
    'Conc.': 'concise',
    'conch.': 'conchology',
    'Conch.': 'conchology',
    'concl.': 'conclusion',
    'Concl.': 'conclusion',
    'concr.': 'concretely',
    'conf.': 'conference, confession',
    'Conf.': 'conference, confession',
    'confid.': 'confidential',
    'Confid.': 'confidential',
    'confl.': 'conflict',
    'Confl.': 'conflict',
    'confut.': 'confutation',
    'Confut.': 'confutation',
    'congr.': 'congress',
    'Congr.': 'congress',
    'congreg.': 'congregation',
    'Congreg.': 'congregation',
    'congress.': 'congressional',
    'Congress.': 'congressional',
    'conj.': 'conjugation, conjunction',
    'conn.': 'Connecticut',
    'Conn.': 'Connecticut',
    'cons.': 'consonant',
    'consc.': 'conscience',
    'Consc.': 'conscience',
    'consecr.': 'consecrated, consecration',
    'Consecr.': 'consecrated, consecration',
    'consid.': 'considerations',
    'Consid.': 'considerations',
    'consol.': 'consolation',
    'Consol.': 'consolation',
    'const.': 'construction, construed with',
    'constit.': 'constitutional',
    'Constit.': 'constitutional',
    'constit. hist.': 'constitutional history',
    'Constit. Hist.': 'constitutional history',
    'constr.': 'construction',
    'Constr.': 'construction',
    'contemp.': 'contemporary',
    'Contemp.': 'contemporary',
    'contempl.': 'contemplation',
    'Contempl.': 'contemplation',
    'contempt.': 'contemptuously',
    'contend.': 'contendings',
    'Contend.': 'contendings',
    'content.': 'contention',
    'Content.': 'contention',
    'contin.': 'continuation',
    'Contin.': 'continuation',
    'contr.': 'contracted, contraction, contrasted',
    'contradict.': 'contradiction',
    'Contradict.': 'contradiction',
    'contrib.': 'contribution',
    'Contrib.': 'contribution',
    'controv.': 'controversial, controversy',
    'Controv.': 'controversial, controversy',
    'conv.': 'convention',
    'Conv.': 'convention',
    'convent.': 'convention',
    'Convent.': 'convention',
    'conversat.': 'conversation',
    'Conversat.': 'conversation',
    'convoc.': 'convocation',
    'Convoc.': 'convocation',
    'cor.': 'Corinthians',
    'Cor.': 'Corinthians',
    'cornw.': 'Cornwall',
    'Cornw.': 'Cornwall',
    'coron.': 'coronation',
    'Coron.': 'coronation',
    'corr.': 'correspondence',
    'Corr.': 'correspondence',
    'corresp.': 'correspondence',
    'Corresp.': 'correspondence',
    'counc.': 'council',
    'Counc.': 'council',
    'courtsh.': 'courtship',
    'Courtsh.': 'courtship',
    'cpd.': 'compound',
    'craniol.': 'craniology',
    'Craniol.': 'craniology',
    'craniom.': 'craniometry',
    'Craniom.': 'craniometry',
    'crim.': 'criminal',
    'Crim.': 'criminal',
    'crim. law': 'criminal law',
    'Crim. Law': 'criminal law',
    'crit.': 'critical, criticism',
    'Crit.': 'critical, criticism',
    'crt.': 'court',
    'Crt.': 'court',
    'crts.': 'courts',
    'Crts.': 'courts',
    'cryptogr.': 'cryptography',
    'Cryptogr.': 'cryptography',
    'crystallogr.': 'crystallography',
    'Crystallogr.': 'crystallography',
    'ct.': 'count, court',
    'Ct.': 'count, court',
    'cumb.': 'Cumberland',
    'Cumb.': 'Cumberland',
    'cumberld.': 'Cumberland',
    'Cumberld.': 'Cumberland',
    'cumbld.': 'Cumberland',
    'Cumbld.': 'Cumberland',
    'cycl.': 'cyclopaedia',
    'Cycl.': 'cyclopaedia',
    'cytol.': 'cytology, cytological',
    'Cytol.': 'cytology, cytological',
    'd.c.': 'District of Columbia',
    'D.C.': 'District of Columbia',
    'dan.': 'Daniel',
    'Dan.': 'Daniel',
    'dat.': 'dative',
    'dau.': 'daughter',
    'Dau.': 'daughter',
    'deb.': 'debate',
    'Deb.': 'debate',
    'dec.': 'December',
    'Dec.': 'December',
    'declar.': 'declaration',
    'Declar.': 'declaration',
    'ded.': 'dedicated, dedication',
    'Ded.': 'dedicated, dedication',
    'def.': 'defence',
    'Def.': 'defence',
    'deliv.': 'deliverance',
    'Deliv.': 'deliverance',
    'dem.': 'demonstrative',
    'demonstr.': 'demonstration',
    'Demonstr.': 'demonstration',
    'dep.': 'department, deputy',
    'Dep.': 'department, deputy',
    'depred.': 'depredation',
    'Depred.': 'depredation',
    'depredat.': 'depredation',
    'Depredat.': 'depredation',
    'dept.': 'department',
    'Dept.': 'department',
    'derbysh.': 'Derbyshire',
    'Derbysh.': 'Derbyshire',
    'deriv.': 'derivative',
    'derog.': 'derogatory',
    'descr.': 'description, descriptive',
    'Descr.': 'description, descriptive',
    'deut.': 'Deuteronomy',
    'Deut.': 'Deuteronomy',
    'devel.': 'development',
    'Devel.': 'development',
    'devonsh.': 'Devonshire',
    'Devonsh.': 'Devonshire',
    'dial.': 'dialect',
    'Dial.': 'dialect',
    'dict.': 'dictionary',
    'Dict.': 'dictionary',
    'diffic.': 'difficult, difficulty',
    'Diffic.': 'difficult, difficulty',
    'dim.': 'diminutive',
    'direct.': 'direction',
    'Direct.': 'direction',
    'dis.': 'diseases',
    'Dis.': 'diseases',
    'disc.': 'discourse',
    'Disc.': 'discourse',
    'discipl.': 'discipline',
    'Discipl.': 'discipline',
    'discov.': 'discovery',
    'Discov.': 'discovery',
    'discrim.': 'discrimination',
    'Discrim.': 'discrimination',
    'discuss.': 'discussion',
    'Discuss.': 'discussion',
    'diss.': 'dissertation',
    'Diss.': 'dissertation',
    'dist.': 'district',
    'Dist.': 'district',
    'distemp.': 'distemper',
    'Distemp.': 'distemper',
    'distill.': 'distilling',
    'Distill.': 'distilling',
    'distrib.': 'distribution',
    'Distrib.': 'distribution',
    'div.': 'divinity, division',
    'Div.': 'divinity, division',
    'divers.': 'diversity',
    'Divers.': 'diversity',
    'dk.': 'Duke',
    'Dk.': 'Duke',
    'doc.': 'documents',
    'Doc.': 'documents',
    'doctr.': 'doctrine',
    'Doctr.': 'doctrine',
    'domest.': 'domestic',
    'Domest.': 'domestic',
    'durh.': 'Durham',
    'Durh.': 'Durham',
    'dyslog.': 'dyslogistic',
    'e.': 'east',
    'E.': 'east, eastern',
    'e. afr.': 'East African',
    'E. Afr.': 'East African',
    'e. angl.': 'East Anglian',
    'E. Angl.': 'East Anglian',
    'e. anglian': 'East Anglian',
    'E. Anglian': 'East Anglian',
    'e. ind.': 'East Indies, East Indian',
    'E. Ind.': 'East Indies, East Indian',
    'e. midl.': 'east midland',
    'e.d.d.': 'English Dialect Dictionary',
    'E.D.D.': 'English Dialect Dictionary',
    'e.e.t.s.': 'Early English Text Society',
    'E.E.T.S.': 'Early English Text Society',
    'east ind.': 'East Indies, East Indian',
    'East Ind.': 'East Indies, East Indian',
    'east.': 'eastern',
    'eccl.': 'Ecclesiastes, ecclesiastical',
    'Eccl.': 'Ecclesiastes, ecclesiastical',
    'eccl. hist.': 'ecclesiastical history',
    'Eccl. Hist.': 'ecclesiastical history',
    'eccl. law': 'ecclesiastical law',
    'Eccl. Law': 'ecclesiastical law',
    'eccles.': 'Ecclesiastes, ecclesiastical',
    'Eccles.': 'Ecclesiastes, ecclesiastical',
    'ecclus.': 'Ecclesiasticus',
    'Ecclus.': 'Ecclesiasticus',
    'ecol.': 'ecology, ecological',
    'Ecol.': 'ecology, ecological',
    'econ.': 'economics, economical',
    'Econ.': 'economics, economical',
    'ed.': 'edition',
    'Ed.': 'Edward, edition',
    'edin.': 'Edinburgh',
    'Edin.': 'Edinburgh',
    'edinb.': 'Edinburgh',
    'Edinb.': 'Edinburgh',
    'educ.': 'education, educational',
    'Educ.': 'education, educational',
    'edw.': 'Edward',
    'Edw.': 'Edward',
    'egypt.': 'Egyptian',
    'Egypt.': 'Egyptian',
    'egyptol.': 'Egyptology',
    'Egyptol.': 'Egyptology',
    'electr.': 'electricity, electrical',
    'Electr.': 'electricity, electrical',
    'electr. engin.': 'electrical engineering',
    'Electr. Engin.': 'electrical engineering',
    'electro-magn.': 'electro-magnetism',
    'Electro-magn.': 'electro-magnetism',
    'electro-physiol.': 'electro-physiology',
    'Electro-physiol.': 'electro-physiology',
    'elem.': 'elements, elementary',
    'Elem.': 'elements, elementary',
    'eliz.': 'Elizabeth',
    'Eliz.': 'Elizabeth',
    'elizab.': 'Elizabethan',
    'Elizab.': 'Elizabethan',
    'ellipt.': 'elliptically',
    'emb.': 'embassy',
    'Emb.': 'embassy',
    'embryol.': 'embryology, embryological',
    'Embryol.': 'embryology, embryological',
    'emph.': 'emphatically',
    'encycl.': 'encyclopaedia, encyclopaedic',
    'Encycl.': 'encyclopaedia, encyclopaedic',
    'encycl. brit.': 'Encyclopaedia Britannica',
    'Encycl. Brit.': 'Encyclopaedia Britannica',
    'encycl. metrop.': 'Encyclopaedia Metropolitana',
    'Encycl. Metrop.': 'Encyclopaedia Metropolitana',
    'eng.': 'England, English',
    'Eng.': 'England, English',
    'engin.': 'engineering',
    'Engin.': 'engineering',
    'englishw.': 'Englishwomen',
    'Englishw.': 'Englishwomen',
    'enq.': 'enquiry',
    'Enq.': 'enquiry',
    'ent.': 'entomology, entomological',
    'Ent.': 'entomology, entomological',
    'enthus.': 'enthusiasm',
    'Enthus.': 'enthusiasm',
    'entom.': 'entomology, entomological',
    'Entom.': 'entomology, entomological',
    'entomol.': 'entomology, entomological',
    'Entomol.': 'entomology, entomological',
    'enzymol.': 'enzymology',
    'Enzymol.': 'enzymology',
    'eoe': 'early Old English',
    'eOE': 'early Old English',
    'ep.': 'epistle',
    'Ep.': 'epistle',
    'eph.': 'Ephesians',
    'Eph.': 'Ephesians',
    'ephes.': 'Ephesians',
    'Ephes.': 'Ephesians',
    'epil.': 'epilogue',
    'Epil.': 'epilogue',
    'episc.': 'episcopacy',
    'Episc.': 'episcopacy',
    'epist.': 'epistle',
    'Epist.': 'epistle',
    'epit.': 'epitaph',
    'Epit.': 'epitaph',
    'equip.': 'equipment',
    'Equip.': 'equipment',
    'erron.': 'erroneously',
    'esd.': 'Esdras',
    'Esd.': 'Esdras',
    'esp.': 'especially',
    'ess.': 'essays',
    'Ess.': 'essays',
    'essent.': 'essential',
    'Essent.': 'essential',
    'establ.': 'establishment',
    'Establ.': 'establishment',
    'esth.': 'Esther',
    'Esth.': 'Esther',
    'ethnol.': 'ethnology',
    'Ethnol.': 'ethnology',
    'etym.': 'etymology',
    'etymol.': 'etymologically',
    'Etymol.': 'etymology, etymological',
    'euphem.': 'euphemistically',
    'eval.': 'evaluation',
    'Eval.': 'evaluation',
    'evang.': 'evangelical',
    'Evang.': 'evangelical',
    'even.': 'evening',
    'Even.': 'evening',
    'evid.': 'evidence',
    'Evid.': 'evidence',
    'evol.': 'evolution, evolutionary',
    'Evol.': 'evolution, evolutionary',
    'ex. doc.': 'executive document',
    'Ex. doc.': 'executive document',
    'exalt.': 'exaltation',
    'Exalt.': 'exaltation',
    'exam.': 'examination',
    'Exam.': 'examination',
    'exc.': 'except',
    'exch.': 'exchange, exchequer',
    'Exch.': 'exchange, exchequer',
    'exec.': 'execution, executive',
    'Exec.': 'execution, executive',
    'exerc.': 'exercises',
    'Exerc.': 'exercises',
    'exhib.': 'exhibition, exhibits',
    'Exhib.': 'exhibition, exhibits',
    'exod.': 'Exodus',
    'Exod.': 'Exodus',
    'exped.': 'expedition',
    'Exped.': 'expedition',
    'exper.': 'experiment, experimental',
    'Exper.': 'experiment, experimental',
    'explan.': 'explanation',
    'Explan.': 'explanation',
    'explic.': 'explication',
    'Explic.': 'explication',
    'explor.': 'exploration',
    'Explor.': 'exploration',
    'expos.': 'exposition, expository',
    'Expos.': 'exposition, expository',
    'ezek.': 'Ezekiel',
    'Ezek.': 'Ezekiel',
    'f.': 'feminine, folio',
    'fab.': 'fables',
    'Fab.': 'fables',
    'fam.': 'familiarly',
    'Fam.': 'family',
    'famil.': 'familiarly',
    'farew.': 'farewell',
    'Farew.': 'farewell',
    'feb.': 'February',
    'Feb.': 'February',
    'fem.': 'feminine',
    'ff.': 'folios',
    'Ff.': 'folios',
    'fifesh.': 'Fifeshire',
    'Fifesh.': 'Fifeshire',
    'fig.': 'figuratively',
    'fl.': 'floruit, flourished',
    'footpr.': 'footprint',
    'Footpr.': 'footprint',
    'forfarsh.': 'Forfarshire',
    'Forfarsh.': 'Forfarshire',
    'fortif.': 'fortification',
    'Fortif.': 'fortification',
    'fortn.': 'fortnightly',
    'Fortn.': 'fortnightly',
    'found.': 'foundations',
    'Found.': 'foundations',
    'fr.': 'French, father',
    'Fr.': 'French, father',
    'fragm.': 'fragments',
    'Fragm.': 'fragments',
    'fratern.': 'fraternity',
    'Fratern.': 'fraternity',
    'freq.': 'frequently',
    'friendsh.': 'friendship',
    'Friendsh.': 'friendship',
    'fund.': 'fundamentals',
    'Fund.': 'fundamentals',
    'furnit.': 'furniture',
    'Furnit.': 'furniture',
    'fut.': 'future',
    'gal.': 'Galatians',
    'Gal.': 'Galatians',
    'gard.': 'garden, gardening',
    'Gard.': 'garden, gardening',
    'gastron.': 'gastronomy',
    'Gastron.': 'gastronomy',
    'gaz.': 'gazette',
    'Gaz.': 'gazette',
    'gd.': 'good',
    'Gd.': 'good',
    'gen.': 'Genesis, general',
    'Gen.': 'Genesis, general',
    'geo.': 'George',
    'Geo.': 'George',
    'geog.': 'geography',
    'Geog.': 'geography',
    'geogr.': 'geography, geographical',
    'Geogr.': 'geography, geographical',
    'geol.': 'geology, geological',
    'Geol.': 'geology, geological',
    'geom.': 'geometry, geometrical',
    'Geom.': 'geometry, geometrical',
    'geomorphol.': 'geomorphology',
    'Geomorphol.': 'geomorphology',
    'ger.': 'German',
    'Ger.': 'German',
    'gerund.': 'gerundial',
    'glac.': 'glaciers',
    'Glac.': 'glaciers',
    'glasg.': 'Glasgow',
    'Glasg.': 'Glasgow',
    'glos.': 'Gloucestershire',
    'Glos.': 'Gloucestershire',
    'gloss.': 'glossary',
    'Gloss.': 'glossary',
    'glouc.': 'Gloucestershire',
    'Glouc.': 'Gloucestershire',
    'gloucestersh.': 'Gloucestershire',
    'Gloucestersh.': 'Gloucestershire',
    'gosp.': 'gospels',
    'Gosp.': 'gospels',
    'gov.': 'government',
    'Gov.': 'government',
    'govt.': 'government',
    'Govt.': 'government',
    'gr.': 'grammar',
    'Gr.': 'grammar',
    'gram.': 'grammar',
    'Gram.': 'grammar',
    'gramm. analysis': 'grammatical analysis',
    'Gramm. Analysis': 'grammatical analysis',
    'gt.': 'great',
    'Gt.': 'great',
    'gynaecol.': 'gynaecology',
    'Gynaecol.': 'gynaecology',
    'hab.': 'Habakkuk',
    'Hab.': 'Habakkuk',
    'haematol.': 'haematology',
    'Haematol.': 'haematology',
    'hag.': 'Haggai',
    'Hag.': 'Haggai',
    'hampsh.': 'Hampshire',
    'Hampsh.': 'Hampshire',
    'handbk.': 'handbook',
    'Handbk.': 'handbook',
    'hants.': 'Hampshire',
    'Hants.': 'Hampshire',
    'heb.': 'Hebrews, Hebrew',
    'Heb.': 'Hebrews, Hebrew',
    'hebr.': 'Hebrews',
    'Hebr.': 'Hebrews',
    'hen.': 'Henry',
    'Hen.': 'Henry',
    'her.': 'heraldry',
    'Her.': 'heraldry',
    'herb.': 'herbalism',
    'Herb.': 'herbalism',
    'heref.': 'Herefordshire',
    'Heref.': 'Herefordshire',
    'hereford.': 'Herefordshire',
    'Hereford.': 'Herefordshire',
    'herefordsh.': 'Herefordshire',
    'Herefordsh.': 'Herefordshire',
    'hertfordsh.': 'Hertfordshire',
    'Hertfordsh.': 'Hertfordshire',
    'hierogl.': 'Hieroglyphic',
    'Hierogl.': 'Hieroglyphic',
    'hist.': 'historical',
    'Hist.': 'history, historical',
    'histol.': 'histology, histological',
    'Histol.': 'histology, histological',
    'hom.': 'homilies',
    'Hom.': 'homilies',
    'horol.': 'horology',
    'Horol.': 'horology',
    'hort.': 'horticulture, horticultural',
    'Hort.': 'horticulture, horticultural',
    'hos.': 'Hosea',
    'Hos.': 'Hosea',
    'hosp.': 'hospital',
    'Hosp.': 'hospital',
    'househ.': 'household',
    'Househ.': 'household',
    'housek.': 'housekeeping',
    'Housek.': 'housekeeping',
    'husb.': 'husbandry',
    'Husb.': 'husbandry',
    'hydraul.': 'hydraulic',
    'Hydraul.': 'hydraulic',
    'hydrol.': 'hydrology, hydrological',
    'Hydrol.': 'hydrology, hydrological',
    'ichth.': 'ichthyology',
    'Ichth.': 'ichthyology',
    'icthyol.': 'icthyology',
    'Icthyol.': 'icthyology',
    'ideol.': 'ideology, ideological',
    'Ideol.': 'ideology, ideological',
    'idol.': 'idolatry',
    'Idol.': 'idolatry',
    'illustr.': 'illustrated, illustrations',
    'Illustr.': 'illustrated, illustrations',
    'imag.': 'imaginary, imagination',
    'Imag.': 'imaginary, imagination',
    'imit.': 'imitative',
    'immunol.': 'immunology',
    'Immunol.': 'immunology',
    'imp.': 'imperative',
    'imperf.': 'imperfect',
    'impers.': 'impersonal',
    'impf.': 'imperfect',
    'impr.': 'imprint, impressions',
    'Impr.': 'imprint, impressions',
    'improp.': 'improperly',
    'inaug.': 'inaugural',
    'Inaug.': 'inaugural',
    'inclos.': 'inclosure',
    'Inclos.': 'inclosure',
    'ind.': 'industry, Indian',
    'Ind.': 'industry, Indian',
    'indef.': 'indefinite',
    'indic.': 'indicative',
    'indir.': 'indirect',
    'industr.': 'industrial',
    'Industr.': 'industrial',
    'industr. rel.': 'industrial relations',
    'Industr. Rel.': 'industrial relations',
    'infin.': 'infinitive',
    'infl.': 'influence',
    'Infl.': 'influence',
    'innoc.': 'innocence, innocent',
    'Innoc.': 'innocence, innocent',
    'inorg.': 'inorganic',
    'Inorg.': 'inorganic',
    'inq.': 'inquiry',
    'Inq.': 'inquiry',
    'inst.': 'institute, institution',
    'Inst.': 'institute, institution',
    'instr.': 'instruction',
    'Instr.': 'instruction',
    'int.': 'interjection',
    'intell.': 'intelligence, intelligent',
    'Intell.': 'intelligence, intelligent',
    'intellect.': 'intellectual',
    'Intellect.': 'intellectual',
    'interc.': 'intercourse',
    'Interc.': 'intercourse',
    'interj.': 'interjection',
    'interl.': 'interlude',
    'Interl.': 'interlude',
    'internat.': 'international',
    'Internat.': 'international',
    'interpr.': 'interpretation',
    'Interpr.': 'interpretation',
    'interrog.': 'interrogative',
    'intr.': 'intransitive',
    'intrans.': 'intransitive',
    'intro.': 'introduction',
    'Intro.': 'introduction',
    'introd.': 'introduction, introductory',
    'Introd.': 'introduction, introductory',
    'inv.': 'inventory, inventories',
    'Inv.': 'inventory, inventories',
    'invent.': 'inventions, inventory, inventories',
    'Invent.': 'inventions, inventory, inventories',
    'invert. zool.': 'invertebrate zoology',
    'Invert. Zool.': 'invertebrate zoology',
    'invertebr.': 'invertebrate, invertebrated',
    'Invertebr.': 'invertebrate, invertebrated',
    'investig.': 'investigation',
    'Investig.': 'investigation',
    'investm.': 'investment',
    'Investm.': 'investment',
    'invoc.': 'invocation',
    'Invoc.': 'invocation',
    'ir.': 'Irish',
    'Ir.': 'Irish',
    'irel.': 'Ireland',
    'Irel.': 'Ireland',
    'iron.': 'ironically',
    'irreg.': 'irregularly',
    'isa.': 'Isaiah',
    'Isa.': 'Isaiah',
    'ital.': 'Italian',
    'Ital.': 'Italian',
    'jahrb.': 'Jahrbuch',
    'Jahrb.': 'Jahrbuch',
    'jam.': 'Jamieson, James',
    'Jam.': 'Jamieson, James',
    'jan.': 'January',
    'Jan.': 'January',
    'jap.': 'Japanese',
    'Jap.': 'Japanese',
    'jas.': 'James, James',
    'Jas.': 'James, James',
    'jer.': 'Jeremiah',
    'Jer.': 'Jeremiah',
    'joc.': 'jocularly',
    'josh.': 'Joshua',
    'Josh.': 'Joshua',
    'jrnl.': 'journal',
    'Jrnl.': 'journal',
    'jrnls.': 'journals',
    'Jrnls.': 'journals',
    'jud.': 'Judges',
    'Jud.': 'Judges',
    'judg.': 'Judges',
    'Judg.': 'Judges',
    'jul.': 'July',
    'Jul.': 'July',
    'jun.': 'June, junior',
    'Jun.': 'June, junior',
    'jurisd.': 'jurisdiction',
    'Jurisd.': 'jurisdiction',
    'jurisdict.': 'jurisdiction',
    'Jurisdict.': 'jurisdiction',
    'jurispr.': 'jurisprudence',
    'Jurispr.': 'jurisprudence',
    'justif.': 'justification',
    'Justif.': 'justification',
    'justific.': 'justification',
    'Justific.': 'justification',
    'k.': 'king',
    'K.': 'king',
    'kent.': 'Kentish',
    'Kent.': 'Kentish',
    'kgs.': 'Kings',
    'Kgs.': 'Kings',
    'king\'s bench div.': 'King\'s Bench Division',
    'King\'s Bench Div.': 'King\'s Bench Division',
    'kingd.': 'kingdom',
    'Kingd.': 'kingdom',
    'knowl.': 'knowledge',
    'Knowl.': 'knowledge',
    'kpr.': 'keeper',
    'Kpr.': 'keeper',
    'l.': 'line',
    'lab.': 'laboratory',
    'Lab.': 'laboratory',
    'lam.': 'Lamentations',
    'Lam.': 'Lamentations',
    'lament': 'lamentation',
    'Lament': 'lamentation',
    'lament.': 'Lamentations',
    'Lament.': 'Lamentations',
    'lanc.': 'Lancashire',
    'Lanc.': 'Lancashire',
    'lancash.': 'Lancashire',
    'Lancash.': 'Lancashire',
    'lancs.': 'Lancashire',
    'Lancs.': 'Lancashire',
    'lang.': 'language',
    'Lang.': 'language',
    'langs.': 'languages',
    'Langs.': 'languages',
    'lat.': 'Latin',
    'Lat.': 'Latin',
    'ld.': 'Lord',
    'Ld.': 'Lord',
    'lds.': 'Lords',
    'Lds.': 'Lords',
    'lect.': 'lectures',
    'Lect.': 'lectures',
    'leechd.': 'leechdom',
    'Leechd.': 'leechdom',
    'leg.': 'legends',
    'Leg.': 'legends',
    'leicest.': 'Leicestershire',
    'Leicest.': 'Leicestershire',
    'leicester.': 'Leicestershire',
    'Leicester.': 'Leicestershire',
    'leicestersh.': 'Leicestershire',
    'Leicestersh.': 'Leicestershire',
    'leics.': 'Leicestershire',
    'Leics.': 'Leicestershire',
    'let.': 'letter',
    'Let.': 'letter',
    'lett.': 'letters',
    'Lett.': 'letters',
    'lev.': 'Leviticus',
    'Lev.': 'Leviticus',
    'lex.': 'lexicon',
    'Lex.': 'lexicon',
    'libr.': 'library',
    'Libr.': 'library',
    'limnol.': 'limnology',
    'Limnol.': 'limnology',
    'lincolnsh.': 'Lincolnshire',
    'Lincolnsh.': 'Lincolnshire',
    'lincs.': 'Lincolnshire',
    'Lincs.': 'Lincolnshire',
    'ling.': 'linguistics',
    'Ling.': 'linguistics',
    'linn.': 'Linnean',
    'Linn.': 'Linnean',
    'lit.': 'literally',
    'Lit.': 'literary, literature',
    'lithogr.': 'lithography',
    'Lithogr.': 'lithography',
    'lithol.': 'lithology',
    'Lithol.': 'lithology',
    'liturg.': 'liturgy',
    'Liturg.': 'liturgy',
    'll.': 'lines',
    'loe': 'late Old English',
    'lOE': 'late Old English',
    'lond.': 'London',
    'Lond.': 'London',
    'lxx': 'Septuagint',
    'LXX': 'Septuagint',
    'm.': 'masculine',
    'macc.': 'Maccabees',
    'Macc.': 'Maccabees',
    'mach.': 'machinery, machines',
    'Mach.': 'machinery, machines',
    'mag.': 'magazine',
    'Mag.': 'magazine',
    'magn.': 'magnetism, magnetic',
    'Magn.': 'magnetism, magnetic',
    'mal.': 'Malachi',
    'Mal.': 'Malachi',
    'man.': 'manual',
    'Man.': 'manual',
    'managem.': 'management',
    'Managem.': 'management',
    'manch.': 'Manchester',
    'Manch.': 'Manchester',
    'manip.': 'manipulation',
    'Manip.': 'manipulation',
    'manuf.': 'manufacturing, manufactures',
    'Manuf.': 'manufacturing, manufactures',
    'mar.': 'March',
    'Mar.': 'March',
    'masc.': 'masculine',
    'mass.': 'Massachussets',
    'Mass.': 'Massachussets',
    'math.': 'mathematics, mathematical',
    'Math.': 'mathematics, mathematical',
    'matt.': 'Matthew',
    'Matt.': 'Matthew',
    'meas.': 'measure',
    'Meas.': 'measure',
    'measurem.': 'measurement',
    'Measurem.': 'measurement',
    'mech.': 'mechanics, mechanical',
    'Mech.': 'mechanics, mechanical',
    'med.': 'medicine, medical',
    'Med.': 'medicine, medical',
    'medit.': 'meditation',
    'Medit.': 'meditation',
    'mem.': 'memoirs',
    'Mem.': 'memoirs',
    'merc.': 'mercury',
    'Merc.': 'mercury',
    'merch.': 'merchants',
    'Merch.': 'merchants',
    'metall.': 'metallurgy',
    'Metall.': 'metallurgy',
    'metallif.': 'metalliferous',
    'Metallif.': 'metalliferous',
    'metallogr.': 'metallography, metallography, metallographical',
    'Metallogr.': 'metallography, metallography, metallographical',
    'metamorph.': 'metamorphosis',
    'Metamorph.': 'metamorphosis',
    'metaph.': 'metaphysics',
    'Metaph.': 'metaphysics',
    'metaphor.': 'metaphorically',
    'meteorol.': 'meteorology, meteorological',
    'Meteorol.': 'meteorology, meteorological',
    'meth.': 'methods',
    'Meth.': 'methods',
    'metr. gr.': 'metri gratia',
    'metrop.': 'metropolitan, metropolis',
    'Metrop.': 'metropolitan, metropolis',
    'mex.': 'Mexican',
    'Mex.': 'Mexican',
    'mic.': 'Micah',
    'Mic.': 'Micah',
    'mich.': 'Michigan',
    'Mich.': 'Michigan',
    'microbiol.': 'microbiology',
    'Microbiol.': 'microbiology',
    'microsc.': 'microscopical',
    'Microsc.': 'microscopical',
    'midl.': 'midlands',
    'mil.': 'military',
    'Mil.': 'military',
    'milit.': 'military',
    'Milit.': 'military',
    'min.': 'mineralogy',
    'Min.': 'mineralogy',
    'mineral.': 'mineralogy, minaralogical',
    'Mineral.': 'mineralogy, minaralogical',
    'misc.': 'miscellaneous, miscellany',
    'Misc.': 'miscellaneous, miscellany',
    'miscell.': 'miscellany',
    'Miscell.': 'miscellany',
    'mispr.': 'misprinted',
    'mod.': 'modern',
    'Mod.': 'modern',
    'monum.': 'monument',
    'Monum.': 'monument',
    'morphol.': 'morphology',
    'Morphol.': 'morphology',
    'ms.': 'manuscript',
    'MS.': 'manuscript',
    'mss.': 'manuscripts',
    'MSS.': 'manuscripts',
    'mt.': 'mount',
    'Mt.': 'mount',
    'mtg.': 'meeting',
    'Mtg.': 'meeting',
    'mts.': 'mountains',
    'Mts.': 'mountains',
    'munic.': 'municipal',
    'Munic.': 'municipal',
    'munif.': 'munificence',
    'Munif.': 'munificence',
    'munim.': 'muniment',
    'Munim.': 'muniment',
    'mus.': 'museum, music, musical',
    'Mus.': 'museum, music, musical',
    'myst.': 'mystery',
    'Myst.': 'mystery',
    'myth.': 'mythology',
    'Myth.': 'mythology',
    'mythol.': 'mythology',
    'Mythol.': 'mythology',
    'n.': 'north, northern',
    'N.': 'north, northern',
    'n. afr.': 'North African',
    'N. Afr.': 'North African',
    'n. amer.': 'North American',
    'N. Amer.': 'North American',
    'n. carolina': 'North Carolina',
    'N. Carolina': 'North Carolina',
    'n. dakota': 'North Dakota',
    'N. Dakota': 'North Dakota',
    'n. ir.': 'Northern Irish',
    'N. Ir.': 'Northern Irish',
    'n. irel.': 'Northern Ireland',
    'N. Irel.': 'Northern Ireland',
    'n.e.': 'north-east, north-eastern',
    'N.E.': 'north-east, north-eastern',
    'n.e.d.': 'New English Dictionary',
    'N.E.D.': 'New English Dictionary',
    'n.s. wales': 'New South Wales',
    'N.S. Wales': 'New South Wales',
    'n.s.w.': 'New South Wales',
    'N.S.W.': 'New South Wales',
    'n.t.': 'New Testament',
    'N.T.': 'New Testament',
    'n.w.': 'north-west, north-western',
    'N.W.': 'north-west, north-western',
    'n.y.': 'New York',
    'N.Y.': 'New York',
    'n.z.': 'New Zealand',
    'N.Z.': 'New Zealand',
    'nah.': 'Nahum',
    'Nah.': 'Nahum',
    'narr.': 'narrative',
    'Narr.': 'narrative',
    'narrat.': 'narrative',
    'Narrat.': 'narrative',
    'nat.': 'natural',
    'Nat.': 'natural',
    'nat. hist.': 'natural history',
    'Nat. Hist.': 'natural history',
    'nat. philos.': 'natural philosophy',
    'Nat. Philos.': 'natural philosophy',
    'nat. sci.': 'natural science',
    'Nat. Sci.': 'natural science',
    'naut.': 'nautical',
    'Naut.': 'nautical',
    'nav.': 'naval, navigation',
    'Nav.': 'naval, navigation',
    'navig.': 'navigation',
    'Navig.': 'navigation',
    'neh.': 'Nehemiah',
    'Neh.': 'Nehemiah',
    'neighb.': 'neighbours, neighbourhood',
    'Neighb.': 'neighbours, neighbourhood',
    'nerv.': 'nervous',
    'Nerv.': 'nervous',
    'neurol.': 'neurology, neurological',
    'Neurol.': 'neurology, neurological',
    'neurosurg.': 'neurosurgery',
    'Neurosurg.': 'neurosurgery',
    'new hampsh.': 'New Hampshire',
    'New Hampsh.': 'New Hampshire',
    'newc.': 'Newcastle',
    'Newc.': 'Newcastle',
    'newspr.': 'newsprint',
    'Newspr.': 'newsprint',
    'no.': 'number',
    'No.': 'number',
    'nom.': 'nominative',
    'nonce-wd.': 'nonce-word',
    'nonconf.': 'nonconformists',
    'non-conf.': 'nonconformists',
    'Nonconf.': 'nonconformists',
    'Non-conf.': 'nonconformists',
    'norf.': 'Norfolk',
    'Norf.': 'Norfolk',
    'north.': 'northern',
    'northamptonsh.': 'Northamptonshire',
    'Northamptonsh.': 'Northamptonshire',
    'northants.': 'Northamptonshire',
    'Northants.': 'Northamptonshire',
    'northumb.': 'Northumberland, Northumbrian',
    'Northumb.': 'Northumberland, Northumbrian',
    'northumbld.': 'Northumberland',
    'Northumbld.': 'Northumberland',
    'northumbr.': 'Northumbrian',
    'Northumbr.': 'Northumbrian',
    'norw.': 'Norwegian',
    'Norw.': 'Norwegian',
    'norweg.': 'Norwegian',
    'Norweg.': 'Norwegian',
    'notts.': 'Nottinghamshire',
    'Notts.': 'Nottinghamshire',
    'nov.': 'November',
    'Nov.': 'November',
    'ns.': 'nouns',
    'nucl.': 'nuclear',
    'Nucl.': 'nuclear',
    'num.': 'Numbers',
    'Num.': 'Numbers',
    'numism.': 'numismatics',
    'Numism.': 'numismatics',
    'o.e.d.': 'Oxford English Dictionary',
    'O.E.D.': 'Oxford English Dictionary',
    'o.t.': 'Old Testament',
    'O.T.': 'Old Testament',
    'obad.': 'Obadiah',
    'Obad.': 'Obadiah',
    'obed.': 'obedience',
    'Obed.': 'obedience',
    'obj.': 'object, objective',
    'Obj.': 'objects',
    'obl.': 'oblique',
    'obs.': 'obsolete',
    'Obs.': 'obsolete',
    'observ.': 'observations',
    'Observ.': 'observations',
    'obstet.': 'obstetrics',
    'Obstet.': 'obstetrics',
    'obstetr.': 'obstetrics',
    'Obstetr.': 'obstetrics',
    'obstetr. med.': 'obstetric medicine',
    'Obstetr. Med.': 'obstetric medicine',
    'occas.': 'occasional',
    'Occas.': 'occasional',
    'occup.': 'occupational',
    'Occup.': 'occupational',
    'occurr.': 'occurrence',
    'Occurr.': 'occurrence',
    'oceanogr.': 'oceanography, oceanographical',
    'Oceanogr.': 'oceanography, oceanographical',
    'oct.': 'October',
    'Oct.': 'October',
    'oe': 'Old English',
    'OE': 'Old English',
    'off.': 'official, office',
    'Off.': 'official, office',
    'offic.': 'official',
    'Offic.': 'official',
    'okla.': 'Oklahoma',
    'Okla.': 'Oklahoma',
    'ont.': 'Ontario',
    'Ont.': 'Ontario',
    'ophthalm.': 'ophthalmology',
    'Ophthalm.': 'ophthalmology',
    'ophthalmol.': 'ophthalmology, ophtalmological',
    'Ophthalmol.': 'ophthalmology, ophtalmological',
    'opp.': 'opposed, opposite',
    'oppress.': 'oppression',
    'Oppress.': 'oppression',
    'opt.': 'optics',
    'Opt.': 'optics',
    'orac.': 'oracles',
    'Orac.': 'oracles',
    'ord.': 'orders, ordinances',
    'Ord.': 'orders, ordinances',
    'org.': 'organic',
    'Org.': 'organic',
    'org. chem.': 'organic chemistry',
    'Org. Chem.': 'organic chemistry',
    'organ. chem.': 'organic chemistry',
    'Organ. Chem.': 'organic chemistry',
    'orig.': 'original',
    'Orig.': 'original',
    'orkn.': 'Orkney',
    'Orkn.': 'Orkney',
    'ornith.': 'ornithology',
    'Ornith.': 'ornithology',
    'ornithol.': 'ornithology, ornithological',
    'Ornithol.': 'ornithology, ornithological',
    'orthogr.': 'orthography',
    'Orthogr.': 'orthography',
    'outl.': 'outline',
    'Outl.': 'outline',
    'oxf.': 'Oxford',
    'Oxf.': 'Oxford',
    'oxfordsh.': 'Oxfordshire',
    'Oxfordsh.': 'Oxfordshire',
    'oxon.': 'Oxfordshire',
    'Oxon.': 'Oxfordshire',
    'p.': 'page',
    'p. r.': 'public records',
    'P. R.': 'public records',
    'pa.': 'past',
    'Pa.': 'Pennsylvania',
    'pa. pple.': 'passive participle, past participle',
    'pa. t.': 'past tense',
    'palaeobot.': 'palaeobotany',
    'Palaeobot.': 'palaeobotany',
    'palaeogr.': 'palaeography',
    'Palaeogr.': 'palaeography',
    'palaeont.': 'palaeontology',
    'Palaeont.': 'palaeontology',
    'palaeontol.': 'palaeontology, palaeontological',
    'Palaeontol.': 'palaeontology, palaeontological',
    'paraphr.': 'paraphrase, paraphrased',
    'Paraphr.': 'paraphrase, paraphrased',
    'parasitol.': 'parasitology',
    'Parasitol.': 'parasitology',
    'parl.': 'parliament, parliamentary',
    'Parl.': 'parliament, parliamentary',
    'parnass.': 'Parnassus',
    'Parnass.': 'Parnassus',
    'pass.': 'passively',
    'path.': 'pathology, pathological',
    'Path.': 'pathology, pathological',
    'pathol.': 'pathology, pathological',
    'Pathol.': 'pathology, pathological',
    'peculat.': 'peculations',
    'Peculat.': 'peculations',
    'penins.': 'peninsula',
    'Penins.': 'peninsula',
    'perf.': 'perfect',
    'Perf.': 'perfect, perfection',
    'perh.': 'perhaps',
    'periodontol.': 'periodontology, periodontological',
    'Periodontol.': 'periodontology, periodontological',
    'pers.': 'personal',
    'Pers.': 'personal, Persian',
    'persec.': 'persecutions',
    'Persec.': 'persecutions',
    'personif.': 'personified',
    'perthsh.': 'Perthshire',
    'Perthsh.': 'Perthshire',
    'pet.': 'Peter',
    'Pet.': 'Peter',
    'petrogr.': 'petrography, petrographical',
    'Petrogr.': 'petrography, petrographical',
    'petrol.': 'petrology, petrological',
    'Petrol.': 'petrology, petrological',
    'pf.': 'perfect',
    'pharm.': 'pharmacology',
    'Pharm.': 'pharmacology',
    'pharmaceut.': 'pharmaceutical',
    'Pharmaceut.': 'pharmaceutical',
    'pharmacol.': 'pharmacology, pharmacological',
    'Pharmacol.': 'pharmacology, pharmacological',
    'phil.': 'Philippians, philosophy, philosophical',
    'Phil.': 'Philippians, philosophy, philosophical',
    'philad.': 'Philadelphia',
    'Philad.': 'Philadelphia',
    'philem.': 'Philemon',
    'Philem.': 'Philemon',
    'philipp.': 'Philippians',
    'Philipp.': 'Philippians',
    'philol.': 'philology, philological',
    'Philol.': 'philology, philological',
    'philos.': 'philosophy, philosophical',
    'Philos.': 'philosophy, philosophical',
    'phoen.': 'Phoenician',
    'Phoen.': 'Phoenician',
    'phonet.': 'phonetically',
    'phonol.': 'phonology',
    'Phonol.': 'phonology',
    'photog.': 'photography',
    'Photog.': 'photography',
    'photogr.': 'photography, photographical',
    'Photogr.': 'photography, photographical',
    'phr.': 'phrase',
    'phrenol.': 'phrenology',
    'Phrenol.': 'phrenology',
    'phys.': 'physiology',
    'Phys.': 'physiology',
    'physical chem.': 'physical chemistry',
    'Physical Chem.': 'physical chemistry',
    'physical geogr.': 'physical geography',
    'Physical Geogr.': 'physical geography',
    'physiogr.': 'physiography',
    'Physiogr.': 'physiography',
    'physiol.': 'physiology, physiological',
    'Physiol.': 'physiology, physiological',
    'pict.': 'pictorial, pictures',
    'Pict.': 'pictorial, pictures',
    'pl.': 'plural',
    'plur.': 'plural',
    'poet.': 'poetical',
    'Poet.': 'poetical',
    'pol.': 'politics, political',
    'Pol.': 'politics, political',
    'pol. econ.': 'political economy',
    'Pol. Econ.': 'political economy',
    'polit.': 'politics, political',
    'Polit.': 'politics, political',
    'polytechn.': 'polytechnical',
    'Polytechn.': 'polytechnical',
    'pop.': 'popular',
    'Pop.': 'popular',
    'porc.': 'porcelain',
    'Porc.': 'porcelain',
    'port.': 'Portuguese',
    'Port.': 'Portuguese',
    'poss.': 'possessive, possible, possibly',
    'posth.': 'posthumously',
    'Posth.': 'posthumously',
    'postm.': 'postmaster',
    'Postm.': 'postmaster',
    'pott.': 'pottery',
    'Pott.': 'pottery',
    'ppl.': 'participial',
    'ppl. a.': 'participial adjective',
    'ppl. adj.': 'participial adjective',
    'ppl. adjs.': 'participial adjectives',
    'pple.': 'participle',
    'pples.': 'participles',
    'pr.': 'present',
    'pr. pple.': 'present participle',
    'pract.': 'practical, practice',
    'Pract.': 'practical, practice',
    'prec.': 'preceding',
    'pred.': 'predicate',
    'predic.': 'predicate, predicatively',
    'predict.': 'prediction',
    'Predict.': 'prediction',
    'pref.': 'preface',
    'Pref.': 'preface',
    'preh.': 'prehistoric',
    'Preh.': 'prehistoric',
    'prehist.': 'prehistory, prehistoric',
    'Prehist.': 'prehistory, prehistoric',
    'prep.': 'prepositional',
    'prerog.': 'prerogative',
    'Prerog.': 'prerogative',
    'pres.': 'present',
    'Pres.': 'present',
    'pres. pple.': 'present participle',
    'presb.': 'Presbyterian, presbytery',
    'Presb.': 'Presbyterian, presbytery',
    'preserv.': 'preservation',
    'Preserv.': 'preservation',
    'prim.': 'primers',
    'Prim.': 'primers',
    'princ.': 'principles',
    'Princ.': 'principles',
    'print.': 'printing',
    'Print.': 'printing',
    'priv.': 'privative',
    'prob.': 'probably',
    'probab.': 'probability, probabilities',
    'Probab.': 'probability, probabilities',
    'probl.': 'problem',
    'Probl.': 'problem',
    'proc.': 'proceedings',
    'Proc.': 'proceedings',
    'prod.': 'products',
    'Prod.': 'products',
    'prol.': 'prologue',
    'Prol.': 'prologue',
    'pron.': 'pronoun, pronunciation',
    'pronunc.': 'pronunciation',
    'Pronunc.': 'pronunciation',
    'prop.': 'properly',
    'Prop.': 'property, properties',
    'propr.': 'proprietary',
    'pros.': 'prosody',
    'Pros.': 'prosody',
    'prov.': 'proverb, proverbial, proverbially',
    'Prov.': 'Proverbs, proverb',
    'provid.': 'providences',
    'Provid.': 'providences',
    'provinc.': 'provincial',
    'Provinc.': 'provincial',
    'provis.': 'provisional',
    'Provis.': 'provisional',
    'ps.': 'Psalms',
    'Ps.': 'Psalms',
    'pseudo-arch.': 'pseudo-archaic',
    'pseudo-dial.': 'pseudo-dialect',
    'pseudo-sc.': 'pseudo-Scots',
    'pseudo-Sc.': 'pseudo-Scots',
    'psych.': 'psychology',
    'Psych.': 'psychology',
    'psychoanal.': 'psychoanalysis',
    'Psychoanal.': 'psychoanalysis',
    'psychoanalyt.': 'psychoanalytic',
    'Psychoanalyt.': 'psychoanalytic',
    'psychol.': 'psychology, psychological',
    'Psychol.': 'psychology, psychological',
    'psychopathol.': 'psychopathology, psychopathological',
    'Psychopathol.': 'psychopathology, psychopathological',
    'pt.': 'part',
    'Pt.': 'part',
    'publ.': 'public, publication',
    'Publ.': 'public, publication',
    'purg.': 'purgatory',
    'Purg.': 'purgatory',
    'q.': 'quarterly, queen',
    'Q.': 'quarterly, queen',
    'q. eliz.': 'Queen Elizabeth',
    'Q. Eliz.': 'Queen Elizabeth',
    'q.v.': 'quod vide, which see',
    'qld.': 'Queensland',
    'Qld.': 'Queensland',
    'quantum mech.': 'quantum mechanics',
    'Quantum Mech.': 'quantum mechanics',
    'queen\'s bench div.': 'Queen\'s Bench Division',
    'Queen\'s Bench Div.': 'Queen\'s Bench Division',
    'quot.': 'quotation',
    'quots.': 'quotations',
    'r.': 'royal',
    'R.': 'royal',
    'r.a.f.': 'Royal Air Force',
    'R.A.F.': 'Royal Air Force',
    'r.c.': 'Roman Catholic',
    'R.C.': 'Roman Catholic',
    'r.c. church': 'Roman Catholic Church',
    'R.C. Church': 'Roman Catholic Church',
    'r.n.': 'Royal Navy',
    'R.N.': 'Royal Navy',
    'radiol.': 'radiology',
    'Radiol.': 'radiology',
    'reas.': 'reasons',
    'Reas.': 'reasons',
    'reb.': 'rebellion',
    'Reb.': 'rebellion',
    'rebell.': 'rebellion',
    'Rebell.': 'rebellion',
    'rec.': 'records',
    'Rec.': 'records',
    'reclam.': 'reclamation',
    'Reclam.': 'reclamation',
    'recoll.': 'recollection',
    'Recoll.': 'recollection',
    'redempt.': 'redemption',
    'Redempt.': 'redemption',
    'redupl.': 'reduplicating',
    'ref.': 'reference, reformation',
    'Ref.': 'reference, reformation',
    'refash.': 'refashioned, refashioning',
    'refl.': 'reflections',
    'Refl.': 'reflections',
    'refus.': 'refusal',
    'Refus.': 'refusal',
    'refut.': 'refutation',
    'Refut.': 'refutation',
    'reg.': 'register',
    'Reg.': 'register',
    'regic.': 'regicide',
    'Regic.': 'regicide',
    'regist.': 'register',
    'Regist.': 'register',
    'regr.': 'register',
    'Regr.': 'register',
    'rel.': 'relating',
    'Rel.': 'relating',
    'relig.': 'religion, religious',
    'Relig.': 'religion, religious',
    'reminisc.': 'reminiscences',
    'Reminisc.': 'reminiscences',
    'remonstr.': 'remonstrance',
    'Remonstr.': 'remonstrance',
    'renfrewsh.': 'Renfrewshire',
    'Renfrewsh.': 'Renfrewshire',
    'rep.': 'report',
    'Rep.': 'report',
    'repr.': 'representative, representing',
    'reprod.': 'reproduction, reproductive',
    'Reprod.': 'reproduction, reproductive',
    'rept.': 'report',
    'Rept.': 'report',
    'repub.': 'republic',
    'Repub.': 'republic',
    'res.': 'research',
    'Res.': 'research',
    'resid.': 'residence, residential',
    'Resid.': 'residence, residential',
    'ret.': 'return',
    'Ret.': 'return',
    'retrosp.': 'retrospective',
    'Retrosp.': 'retrospective',
    'rev.': 'review, Revelation',
    'Rev.': 'review, Revelation',
    'revol.': 'revolution',
    'Revol.': 'revolution',
    'rhet.': 'rhetoric',
    'Rhet.': 'rhetoric',
    'rhode isl.': 'Rhode Island',
    'Rhode Isl.': 'Rhode Island',
    'rich.': 'Richard',
    'Rich.': 'Richard',
    'rom.': 'Roman, Romans',
    'Rom.': 'Roman, Romans',
    'rom. antiq.': 'Roman antiquities',
    'Rom. Antiq.': 'Roman antiquities',
    'ross-sh.': 'Ross-shire',
    'Ross-sh.': 'Ross-shire',
    'roxb.': 'Roxburgh',
    'Roxb.': 'Roxburgh',
    'roy.': 'royal',
    'Roy.': 'royal',
    'rudim.': 'rudiments',
    'Rudim.': 'rudiments',
    'russ.': 'Russia, Russian',
    'Russ.': 'Russia, Russian',
    's.': 'south',
    'S.': 'south, southern',
    's. afr.': 'South African',
    'S. Afr.': 'South African',
    's. carolina': 'South Carolina',
    'S. Carolina': 'South Carolina',
    's. dakota': 'South Dakota',
    'S. Dakota': 'South Dakota',
    's.e.': 'south-east, south-eastern',
    'S.E.': 'south-east, south-eastern',
    's.t.s.': 'Scottish Text Society',
    'S.T.S.': 'Scottish Text Society',
    's.v.': 'sub verbo, under the word',
    's.w.': 'south-west, south-western',
    'S.W.': 'south-west, south-western',
    'sam.': 'Samuel',
    'Sam.': 'Samuel',
    'sask.': 'Saskatchewan',
    'Sask.': 'Saskatchewan',
    'sat.': 'Saturday',
    'Sat.': 'Saturday',
    'sax.': 'Saxon',
    'Sax.': 'Saxon',
    'sc.': 'scilicet, understand or supply',
    'Sc.': 'Scottish, Scots',
    'scand.': 'Scandinavia, Scandinavian',
    'Scand.': 'Scandinavia, Scandinavian',
    'sch.': 'school',
    'Sch.': 'school',
    'sci.': 'sciences, scientific',
    'Sci.': 'sciences, scientific',
    'scot.': 'Scottish',
    'Scot.': 'Scottish',
    'scotl.': 'Scotland',
    'Scotl.': 'Scotland',
    'script.': 'scripture',
    'Script.': 'scripture',
    'sculpt.': 'sculpture',
    'Sculpt.': 'sculpture',
    'seismol.': 'seismology',
    'Seismol.': 'seismology',
    'sel.': 'selected',
    'Sel.': 'selected',
    'sel. comm.': 'select committee',
    'Sel. comm.': 'select committee',
    'select.': 'selection',
    'Select.': 'selection',
    'sept.': 'September',
    'Sept.': 'September',
    'ser.': 'series',
    'Ser.': 'series',
    'serm.': 'sermons',
    'Serm.': 'sermons',
    'sess.': 'session',
    'Sess.': 'session',
    'settlem.': 'settlement',
    'Settlem.': 'settlement',
    'sev.': 'several',
    'Sev.': 'several',
    'shakes.': 'Shakespeare',
    'Shakes.': 'Shakespeare',
    'shaks.': 'Shakespeare',
    'Shaks.': 'Shakespeare',
    'sheph.': 'shepherd',
    'Sheph.': 'shepherd',
    'shetl.': 'Shetland',
    'Shetl.': 'Shetland',
    'shropsh.': 'Shropshire',
    'Shropsh.': 'Shropshire',
    'sing.': 'singular',
    'soc.': 'society',
    'Soc.': 'society',
    'sociol.': 'sociology, sociological',
    'Sociol.': 'sociology, sociological',
    'som.': 'Somerset',
    'Som.': 'Somerset',
    'song of sol.': 'Song of Solomon',
    'Song of Sol.': 'Song of Solomon',
    'song sol.': 'Song of Solomon',
    'Song Sol.': 'Song of Solomon',
    'sonn.': 'sonnet',
    'Sonn.': 'sonnet',
    'south.': 'southern',
    'sp.': 'spelling',
    'span.': 'Spanish',
    'Span.': 'Spanish',
    'spec.': 'specifically, special',
    'Spec.': 'specimens, special',
    'specif.': 'specifications',
    'Specif.': 'specifications',
    'specim.': 'specimens',
    'Specim.': 'specimens',
    'spectrosc.': 'spectroscopy',
    'Spectrosc.': 'spectroscopy',
    'ss.': 'saints',
    'SS.': 'saints',
    'st.': 'Saint, street',
    'St.': 'Saint, street',
    'staff.': 'Staffordshire',
    'Staff.': 'Staffordshire',
    'stafford.': 'Staffordshire',
    'Stafford.': 'Staffordshire',
    'staffordsh.': 'Staffordshire',
    'Staffordsh.': 'Staffordshire',
    'staffs.': 'Staffordshire',
    'Staffs.': 'Staffordshire',
    'stand.': 'standard',
    'Stand.': 'standard',
    'stat.': 'statistical',
    'Stat.': 'statistical',
    'statist.': 'statistical',
    'Statist.': 'statistical',
    'stock exch.': 'stock exchange',
    'Stock Exch.': 'stock exchange',
    'str.': 'strong',
    'stratigr.': 'stratigraphy, stratigraphical',
    'Stratigr.': 'stratigraphy, stratigraphical',
    'struct.': 'structure, structural',
    'Struct.': 'structure, structural',
    'stud.': 'studies',
    'Stud.': 'studies',
    'subj.': 'subjects',
    'Subj.': 'subjects',
    'subjunct.': 'subjunctive',
    'subord.': 'subordinate',
    'subord. cl.': 'subordinate clause',
    'subscr.': 'subscription',
    'Subscr.': 'subscription',
    'subscript.': 'subscription',
    'Subscript.': 'subscription',
    'subseq.': 'subsequently',
    'subst.': 'substantively',
    'suff.': 'suffix',
    'Suff.': 'Suffolk',
    'superl.': 'superlative',
    'suppl.': 'supplement, supplementary',
    'Suppl.': 'supplement, supplementary',
    'supplic.': 'supplications',
    'Supplic.': 'supplications',
    'suppress.': 'suppression',
    'Suppress.': 'suppression',
    'surg.': 'surgery, surgical',
    'Surg.': 'surgery, surgical',
    'surv.': 'survey, surveying',
    'Surv.': 'survey, surveying',
    'sus.': 'Susanna',
    'Sus.': 'Susanna',
    'syll.': 'syllable',
    'symmetr.': 'symmetrical',
    'Symmetr.': 'symmetrical',
    'symp.': 'symposium',
    'Symp.': 'symposium',
    'syst.': 'system',
    'Syst.': 'system',
    't.': 'tense',
    'taxon.': 'taxonomy, taxonomic',
    'Taxon.': 'taxonomy, taxonomic',
    'techn.': 'technical',
    'Techn.': 'technical',
    'technol.': 'technology, technological',
    'Technol.': 'technology, technological',
    'tel.': 'telegraph',
    'Tel.': 'telegraph',
    'telecomm.': 'telecommunications',
    'Telecomm.': 'telecommunications',
    'telegr.': 'telegraph, telegraphy, telegraphical',
    'Telegr.': 'telegraph, telegraphy, telegraphical',
    'teleph.': 'telephony, telephonic',
    'Teleph.': 'telephony, telephonic',
    'teratol.': 'teratology',
    'Teratol.': 'teratology',
    'terminol.': 'terminology, terminological',
    'Terminol.': 'terminology, terminological',
    'terrestr.': 'terrestrial',
    'Terrestr.': 'terrestrial',
    'test.': 'testament',
    'Test.': 'testament',
    'textbk.': 'textbook',
    'Textbk.': 'textbook',
    'theat.': 'theatre, theatrical',
    'Theat.': 'theatre, theatrical',
    'theatr.': 'theatre, theatrical',
    'Theatr.': 'theatre, theatrical',
    'theol.': 'theology, theological',
    'Theol.': 'theology, theological',
    'theoret.': 'theoretical',
    'Theoret.': 'theoretical',
    'thermonucl.': 'thermonuclear',
    'Thermonucl.': 'thermonuclear',
    'thes.': 'thesaurus',
    'Thes.': 'thesaurus',
    'thess.': 'Thessalonians',
    'Thess.': 'Thessalonians',
    'tim.': 'Timothy',
    'Tim.': 'Timothy',
    'tit.': 'Titus',
    'Tit.': 'Titus',
    'topogr.': 'topography, topographical',
    'Topogr.': 'topography, topographical',
    'tr.': 'translation, translating',
    'trad.': 'tradition, traditional',
    'Trad.': 'tradition, traditional',
    'trag.': 'tragedy',
    'Trag.': 'tragedy',
    'trans.': 'transactions',
    'Trans.': 'transactions',
    'transf.': 'transferred sense',
    'transl.': 'translation',
    'Transl.': 'translation',
    'transubstant.': 'transubstantiation',
    'Transubstant.': 'transubstantiation',
    'trav.': 'travels',
    'Trav.': 'travels',
    'treas.': 'treasurer, treasury',
    'Treas.': 'treasurer, treasury',
    'treat.': 'treatise',
    'Treat.': 'treatise',
    'treatm.': 'treatment',
    'Treatm.': 'treatment',
    'trib.': 'tribune',
    'Trib.': 'tribune',
    'trig.': 'trigonometry',
    'Trig.': 'trigonometry',
    'trigonom.': 'trigonometry',
    'Trigonom.': 'trigonometry',
    'trop.': 'tropical',
    'Trop.': 'tropical',
    'troub.': 'troublesome',
    'Troub.': 'troublesome',
    'troubl.': 'troublesome',
    'Troubl.': 'troublesome',
    'typog.': 'typography',
    'Typog.': 'typography',
    'typogr.': 'typography',
    'Typogr.': 'typography',
    'u.k.': 'United Kingdom',
    'U.K.': 'United Kingdom',
    'u.s.': 'United States',
    'U.S.': 'United States',
    'u.s.a.': 'United States of America',
    'U.S.A.': 'United States of America',
    'u.s.a.f.': 'United States Air Force',
    'U.S.A.F.': 'United States Air Force',
    'u.s.s.r.': 'Union of Soviet Socialist Republics',
    'U.S.S.R.': 'Union of Soviet Socialist Republics',
    'ult.': 'ultimately',
    'univ.': 'university',
    'Univ.': 'university',
    'unkn.': 'unknown',
    'unnat.': 'unnatural',
    'Unnat.': 'unnatural',
    'unoffic.': 'unofficial',
    'Unoffic.': 'unofficial',
    'unstr.': 'unstressed',
    'urin.': 'urinary',
    'Urin.': 'urinary',
    'usu.': 'usually',
    'utilit.': 'utilitarian',
    'Utilit.': 'utilitarian',
    'v.': 'verb',
    'v.r.': 'variant reading',
    'v.rr.': 'variant readings',
    'va.': 'Virginia',
    'Va.': 'Virginia',
    'vac.': 'vacation',
    'Vac.': 'vacation',
    'valedict.': 'valediction',
    'Valedict.': 'valediction',
    'var.': 'variant',
    'varr.': 'variants',
    'vars.': 'variants',
    'vb.': 'verb',
    'vbl.': 'verbal',
    'vbl. ns.': 'verbal nouns',
    'vbl.n.': 'verbal noun',
    'vbs.': 'verbs',
    'veg.': 'vegetable',
    'Veg.': 'vegetable',
    'veg. phys.': 'vegetable physiology',
    'Veg. Phys.': 'vegetable physiology',
    'veg. physiol.': 'vegetable physiology',
    'Veg. Physiol.': 'vegetable physiology',
    'venet.': 'Venetian',
    'Venet.': 'Venetian',
    'vertebr.': 'vertebrate',
    'Vertebr.': 'vertebrate',
    'vet.': 'veterinary, veterinary science',
    'Vet.': 'veterinary, veterinary science',
    'vet. med.': 'veterinary medicine',
    'Vet. Med.': 'veterinary medicine',
    'vet. path.': 'veterinary pathology',
    'Vet. Path.': 'veterinary pathology',
    'vet. sci.': 'veterinary science',
    'Vet. Sci.': 'veterinary science',
    'vet. surg.': 'veterinary surgery',
    'Vet. Surg.': 'veterinary surgery',
    'vic.': 'Victoria',
    'Vic.': 'Victoria',
    'vict.': 'Victoria',
    'Vict.': 'Victoria',
    'vind.': 'vindication, vindicated',
    'Vind.': 'vindication, vindicated',
    'vindic.': 'vindication, vindicated',
    'Vindic.': 'vindication, vindicated',
    'virg.': 'virgins',
    'Virg.': 'virgins',
    'virol.': 'virology',
    'Virol.': 'virology',
    'viz.': 'videlicet, namely',
    'voc.': 'vocabulary',
    'Voc.': 'vocabulary',
    'vocab.': 'vocabulary',
    'Vocab.': 'vocabulary',
    'vol.': 'volume',
    'Vol.': 'volume',
    'vols.': 'volumes',
    'Vols.': 'volumes',
    'voy.': 'voyages',
    'Voy.': 'voyages',
    'vulg.': 'vulgarly',
    'Vulg.': 'Vulgate, vulgar',
    'w.': 'west',
    'W.': 'west, western',
    'w. afr.': 'West African',
    'W. Afr.': 'West African',
    'w. ind.': 'West Indies, West Indian',
    'W. Ind.': 'West Indies, West Indian',
    'w. indies': 'West Indies',
    'W. Indies': 'West Indies',
    'w. va.': 'West Virginia',
    'W. Va.': 'West Virginia',
    'warwicksh.': 'Warwickshire',
    'Warwicksh.': 'Warwickshire',
    'wd.': 'word',
    'Wd.': 'word',
    'west.': 'western',
    'westm.': 'Westminster',
    'Westm.': 'Westminster',
    'westmld.': 'Westmoreland',
    'Westmld.': 'Westmoreland',
    'westmorld.': 'Westmoreland',
    'Westmorld.': 'Westmoreland',
    'westmrld.': 'Westmoreland',
    'Westmrld.': 'Westmoreland',
    'will.': 'William',
    'Will.': 'William',
    'wilts.': 'Wiltshire',
    'Wilts.': 'Wiltshire',
    'wiltsh.': 'Wiltshire',
    'Wiltsh.': 'Wiltshire',
    'wis.': 'Wisconsin',
    'Wis.': 'Wisconsin',
    'wisd.': 'Wisdom of Solomon, wisdom',
    'Wisd.': 'Wisdom of Solomon, wisdom',
    'wk.': 'weak',
    'Wk.': 'week, work',
    'wkly.': 'weekly',
    'Wkly.': 'weekly',
    'wks.': 'works',
    'Wks.': 'works',
    'wonderf.': 'wonderful',
    'Wonderf.': 'wonderful',
    'worc.': 'Worcestershire',
    'Worc.': 'Worcestershire',
    'worcestersh.': 'Worcestershire',
    'Worcestersh.': 'Worcestershire',
    'worcs.': 'Worcestershire',
    'Worcs.': 'Worcestershire',
    'writ.': 'writings',
    'Writ.': 'writings',
    'yearbk.': 'yearbook',
    'Yearbk.': 'yearbook',
    'yng.': 'young',
    'Yng.': 'young',
    'yorks.': 'Yorkshire',
    'Yorks.': 'Yorkshire',
    'yorksh.': 'Yorkshire',
    'Yorksh.': 'Yorkshire',
    'yr.': 'year',
    'Yr.': 'year',
    'yrs.': 'years',
    'Yrs.': 'years',
    'zech.': 'Zechariah',
    'Zech.': 'Zechariah',
    'zeitschr.': 'Zeitschrift',
    'Zeitschr.': 'Zeitschrift',
    'zeph.': 'Zephaniah',
    'Zeph.': 'Zephaniah',
    'zoogeogr.': 'zoogeography',
    'Zoogeogr.': 'zoogeography',
    'zool.': 'zoology, zoological',
    'Zool.': 'zoology, zoological',
  };
}
