// // Copyright ©2022, GM Consult (Pty) Ltd. All rights reserved. End user is
// // granted a non-exclusive non-transferable license the ("License") to use GM
// // Consult's proprietary software (the "Software").

// // ignore_for_file: public_member_api_docs

// class English {
//   const English();
// //

//   static const nonWordChars = r"[^a-zA-z\&'-]";

//   static const abbreviations = [
//     'Anon.',
//     'Arb.',
//     'Ashm.',
//     'Jam.',
//     'a',
//     'c',
//     'eOE',
//     'lOE',
//     'OE',
//     'Bel & Dr.',
//     'Ecclus.',
//     'Esd.',
//     'Macc.',
//     'Sus.',
//     'Wisd.',
//     'Chr.',
//     'Chron.',
//     'Col.',
//     'Coloss.',
//     'Cor.',
//     'Dan.',
//     'Deut.',
//     'Eccl.',
//     'Eccles.',
//     'Eph.',
//     'Ephes.',
//     'Esth.',
//     'Exod.',
//     'Ezek.',
//     'Gal.',
//     'Gen.',
//     'Hab.',
//     'Hag.',
//     'Heb.',
//     'Hebr.',
//     'Hos.',
//     'Isa.',
//     'Jas.',
//     'Jer.',
//     'Josh.',
//     'Jud.',
//     'Judg.',
//     'Kgs.',
//     'Lam.',
//     'Lament.',
//     'Lev.',
//     'Mal.',
//     'Matt.',
//     'Mic.',
//     'Nah.',
//     'Neh.',
//     'Num.',
//     'Obad.',
//     'Pet.',
//     'Philem.',
//     'Phil.',
//     'Philipp.',
//     'Prov.',
//     'Ps.',
//     'Rev.',
//     'Rom.',
//     'Sam.',
//     'Song of Sol.',
//     'Song Sol.',
//     'Thess.',
//     'Tim.',
//     'Tit.',
//     'Zech.',
//     'Zeph.',
//     'abbrev.',
//     'Abd.',
//     'Aberd.',
//     'Aberdeensh.',
//     'abl.',
//     'Abol.',
//     'Aborig.',
//     'Abr.',
//     'Abridg.',
//     'Abridgem.',
//     'Absol.',
//     'abstr.',
//     'Abst.',
//     'Acad.',
//     'Accept.',
//     'Accomm.',
//     'Accompl.',
//     'acc.',
//     'Acct.',
//     'Accs.',
//     'Accts.',
//     'accus.',
//     'Achievem.',
//     'ad.',
//     'Add.',
//     'Addit.',
//     'Addr.',
//     'adj. phr.',
//     'adj.',
//     'adjs.',
//     'Admin.',
//     'Adm.',
//     'Admir.',
//     'Admon.',
//     'Admonit.',
//     'Adv.',
//     'Advancem.',
//     'advb.',
//     'advs.',
//     'Advert.',
//     'Advt.',
//     'Advts.',
//     'Advoc.',
//     'Aerodynam.',
//     'Aeronaut.',
//     'Aff.',
//     'Affect.',
//     'Afr.',
//     'agst.',
//     'Agric.',
//     'Alch.',
//     'Alg.',
//     'Alleg.',
//     'Allit.',
//     'Alm.',
//     'Alph.',
//     'alt.',
//     'Amer.',
//     'Anal.',
//     'Analyt.',
//     'Anat.',
//     'Anc.',
//     'Anecd.',
//     'Ang.',
//     'Angl.',
//     'Anglo-Ind.',
//     'Anim.',
//     'Ann.',
//     'Anniv.',
//     'A.D.',
//     'Annot.',
//     'Answ.',
//     'Anthrop.',
//     'Anthropol.',
//     'Ant.',
//     'Antiq.',
//     'aphet.',
//     'Apoc.',
//     'Apol.',
//     'app.',
//     'Applic.',
//     'Appl.',
//     'appos.',
//     'Apr.',
//     'Arab.',
//     'Archaeol.',
//     'arch.',
//     'Abp.',
//     'Archipel.',
//     'Archit.',
//     'Argt.',
//     'Arith.',
//     'Arithm.',
//     'Arrangem.',
//     'art.',
//     'Artic.',
//     'Artific.',
//     'Artill.',
//     'Assemb.',
//     'Assoc.',
//     'Assoc. Football',
//     'Assyriol.',
//     'Astrol.',
//     'Astronaut.',
//     'Astr.',
//     'Astron.',
//     'Att.',
//     'Attrib.',
//     'Aug.',
//     'Austral.',
//     'Auth.',
//     'A.V.',
//     'Autobiog.',
//     'Autobiogr.',
//     'Ayrsh.',
//     'Bacteriol.',
//     'Bedford.',
//     'Bedfordsh.',
//     'bef.',
//     'B.C.',
//     'Belg.',
//     'Berks.',
//     'Berksh.',
//     'Berw.',
//     'Berwicksh.',
//     'betw.',
//     'Bibliogr.',
//     'Biochem.',
//     'Biog.',
//     'Biogr.',
//     'Biol.',
//     'Bp.',
//     'Bk.',
//     'Bks.',
//     'Bord.',
//     'Bot.',
//     'Braz.',
//     'Brit.',
//     'BNC',
//     'Bucks.',
//     'Build.',
//     'Bull.',
//     'Bur.',
//     'Calc.',
//     'Cal.',
//     'Calend.',
//     'Calif.',
//     'Calligr.',
//     'Camb.',
//     'Cambr.',
//     'Campanol.',
//     'Canad.',
//     'Canterb.',
//     'Capt.',
//     'Cartogr.',
//     'Catal.',
//     'Catech.',
//     'Cath.',
//     'Cent.',
//     'c.',
//     'Ceram.',
//     'Cert.',
//     'Certif.',
//     'Chamb.',
//     'Char.',
//     'Charac.',
//     'Chas.',
//     'Chem. Engin.',
//     'Chem.',
//     'Chesh.',
//     'Chrons.',
//     'Chronol.',
//     'Ch.',
//     'Ch. Hist.',
//     'Cinematogr.',
//     'Circ.',
//     'Civil Engin.',
//     'Civ. Law',
//     'Class.',
//     'Class. Antiq.',
//     'Classif.',
//     'cl.',
//     'Climatol.',
//     'Clin.',
//     'cogn. w.',
//     'Coll.',
//     'Collect.',
//     'colloq.',
//     'Comb.',
//     'Combs.',
//     'comb. form',
//     'Commandm.',
//     'Commend.',
//     'Comm.',
//     'Commerc.',
//     'Comm. Law',
//     'Com.',
//     'Commiss.',
//     'Commonw.',
//     'Communic.',
//     'Comp.',
//     'Compan.',
//     'compar.',
//     'Comp. Anat.',
//     'Compend.',
//     'compl.',
//     'Compos.',
//     'cpd.',
//     'conc.',
//     'Conch.',
//     'Concl.',
//     'concr.',
//     'cf.',
//     'Conf.',
//     'Confid.',
//     'Confl.',
//     'Confut.',
//     'Congreg.',
//     'Congr.',
//     'Congress.',
//     'conj.',
//     'Conn.',
//     'Consc.',
//     'Consecr.',
//     'Consid.',
//     'Consol.',
//     'cons.',
//     'Constit.',
//     'Constit. Hist.',
//     'Constr.',
//     'const.',
//     'Contempl.',
//     'Contemp.',
//     'contempt.',
//     'Contend.',
//     'Content.',
//     'Contin.',
//     'contr.',
//     'Contradict.',
//     'Contrib.',
//     'Controv.',
//     'Conv.',
//     'Convent.',
//     'Conversat.',
//     'Convoc.',
//     'Cornw.',
//     'Coron.',
//     'Corr.',
//     'Corresp.',
//     'Counc.',
//     'Ct.',
//     'Crt.',
//     'Crts.',
//     'Courtsh.',
//     'Craniol.',
//     'Craniom.',
//     'Crim.',
//     'Crim. Law',
//     'Crit.',
//     'Cryptogr.',
//     'Crystallogr.',
//     'Cumb.',
//     'Cumberld.',
//     'Cumbld.',
//     'Cycl.',
//     'Cytol.',
//     'dat.',
//     'Dau.',
//     'Deb.',
//     'Dec.',
//     'Declar.',
//     'Ded.',
//     'Def.',
//     'Deliv.',
//     'Demonstr.',
//     'dem.',
//     'Dep.',
//     'Dept.',
//     'Depred.',
//     'Depredat.',
//     'Derbysh.',
//     'deriv.',
//     'derog.',
//     'Descr.',
//     'Devel.',
//     'Devonsh.',
//     'dial.',
//     'Dict.',
//     'Diffic.',
//     'dim.',
//     'Direct.',
//     'Discipl.',
//     'Disc.',
//     'Discov.',
//     'Discrim.',
//     'Discuss.',
//     'Dis.',
//     'Diss.',
//     'Distemp.',
//     'Distill.',
//     'Distrib.',
//     'Dist.',
//     'D.C.',
//     'Divers.',
//     'Div.',
//     'Doctr.',
//     'Doc.',
//     'Domest.',
//     'Dk.',
//     'Durh.',
//     'dyslog.',
//     'E.E.T.S.',
//     'e.',
//     'E. Afr.',
//     'E. Angl.',
//     'E. Anglian',
//     'East Ind.',
//     'E. Ind.',
//     'e. midl.',
//     'east.',
//     'Eccl. Hist.',
//     'Eccl. Law',
//     'Ecol.',
//     'Econ.',
//     'Edin.',
//     'Edinb.',
//     'ed.',
//     'Educ.',
//     'Edw.',
//     'Egypt.',
//     'Egyptol.',
//     'Electr. Engin.',
//     'Electr.',
//     'Electro-magn.',
//     'Electro-physiol.',
//     'Elem.',
//     'Eliz.',
//     'Elizab.',
//     'ellipt.',
//     'Emb.',
//     'Embryol.',
//     'emph.',
//     'Encycl. Brit.',
//     'Encycl. Metrop.',
//     'Encycl.',
//     'Engin.',
//     'Eng.',
//     'E.D.D.',
//     'Englishw.',
//     'Enq.',
//     'Enthus.',
//     'Ent.',
//     'Entom.',
//     'Entomol.',
//     'Enzymol.',
//     'Epil.',
//     'Episc.',
//     'Ep.',
//     'Epist.',
//     'Epit.',
//     'Equip.',
//     'erron.',
//     'esp.',
//     'Ess.',
//     'Essent.',
//     'Establ.',
//     'Ethnol.',
//     'etymol.',
//     'etym.',
//     'euphem.',
//     'Eval.',
//     'Evang.',
//     'Even.',
//     'Evid.',
//     'Evol.',
//     'Exalt.',
//     'Exam.',
//     'exc.',
//     'Exch.',
//     'Exec.',
//     'Ex. doc.',
//     'Exerc.',
//     'Exhib.',
//     'Exped.',
//     'Exper.',
//     'Explan.',
//     'Explic.',
//     'Explor.',
//     'Expos.',
//     'Fab.',
//     'fam.',
//     'famil.',
//     'Farew.',
//     'Fr.',
//     'Feb.',
//     'f.',
//     'fem.',
//     'Fifesh.',
//     'fig.',
//     'fl.',
//     'Ff.',
//     'Footpr.',
//     'Forfarsh.',
//     'Fortif.',
//     'Fortn.',
//     'Found.',
//     'Fragm.',
//     'Fratern.',
//     'freq.',
//     'Friendsh.',
//     'Fund.',
//     'Furnit.',
//     'fut.',
//     'Gard.',
//     'Gastron.',
//     'Gaz.',
//     'Geog.',
//     'Geogr.',
//     'Geol.',
//     'Geom.',
//     'Geomorphol.',
//     'Geo.',
//     'Ger.',
//     'gerund.',
//     'Glac.',
//     'Glasg.',
//     'Gloss.',
//     'Glos.',
//     'Glouc.',
//     'Gloucestersh.',
//     'Gd.',
//     'Gosp.',
//     'Gov.',
//     'Govt.',
//     'Gr.',
//     'Gram.',
//     'Gramm. Analysis',
//     'Gt.',
//     'Gynaecol.',
//     'Haematol.',
//     'Hampsh.',
//     'Hants.',
//     'Handbk.',
//     'Hen.',
//     'Her.',
//     'Herb.',
//     'Heref.',
//     'Hereford.',
//     'Herefordsh.',
//     'Hertfordsh.',
//     'Hierogl.',
//     'Histol.',
//     'hist.',
//     'Hom.',
//     'Horol.',
//     'Hort.',
//     'Hosp.',
//     'Househ.',
//     'Housek.',
//     'Husb.',
//     'Hydraul.',
//     'Hydrol.',
//     'Ichth.',
//     'Icthyol.',
//     'Ideol.',
//     'Idol.',
//     'Illustr.',
//     'Imag.',
//     'imit.',
//     'Immunol.',
//     'imp.',
//     'imperf.',
//     'impf.',
//     'impers.',
//     'Impr.',
//     'improp.',
//     'Inaug.',
//     'Inclos.',
//     'indef.',
//     'Ind.',
//     'indic.',
//     'indir.',
//     'Industr.',
//     'Industr. Rel.',
//     'infin.',
//     'Infl.',
//     'Innoc.',
//     'Inorg.',
//     'Inq.',
//     'Inst.',
//     'Instr.',
//     'Intellect.',
//     'Intell.',
//     'Interc.',
//     'int.',
//     'interj.',
//     'Interl.',
//     'Internat.',
//     'Interpr.',
//     'interrog.',
//     'intr.',
//     'intrans.',
//     'Intro.',
//     'Introd.',
//     'Invent.',
//     'Inv.',
//     'Invert. Zool.',
//     'Invertebr.',
//     'Investig.',
//     'Investm.',
//     'Invoc.',
//     'Irel.',
//     'Ir.',
//     'iron.',
//     'irreg.',
//     'Ital.',
//     'Jahrb.',
//     'Jan.',
//     'Jap.',
//     'joc.',
//     'Jrnl.',
//     'Jrnls.',
//     'Jul.',
//     'Jun.',
//     'Jurisd.',
//     'Jurisdict.',
//     'Jurispr.',
//     'Justif.',
//     'Justific.',
//     'Kpr.',
//     'Kent.',
//     'K.',
//     'King’s Bench Div.',
//     'Kingd.',
//     'Knowl.',
//     'Lab.',
//     'Lament',
//     'Lanc.',
//     'Lancash.',
//     'Lancs.',
//     'Lang.',
//     'Langs.',
//     'Lat.',
//     'Lect.',
//     'Leechd.',
//     'Leg.',
//     'Leicest.',
//     'Leicester.',
//     'Leicestersh.',
//     'Leics.',
//     'Let.',
//     'Lett.',
//     'Lex.',
//     'Libr.',
//     'Limnol.',
//     'Lincolnsh.',
//     'Lincs.',
//     'l.',
//     'll.',
//     'Ling.',
//     'Linn.',
//     'lit.',
//     'Lithogr.',
//     'Lithol.',
//     'Liturg.',
//     'Lond.',
//     'Ld.',
//     'Lds.',
//     'Mach.',
//     'Mag.',
//     'Magn.',
//     'Managem.',
//     'Manch.',
//     'Manip.',
//     'Man.',
//     'Manuf.',
//     'MS.',
//     'MSS.',
//     'Mar.',
//     'm.',
//     'masc.',
//     'Mass.',
//     'Math.',
//     'Meas.',
//     'Measurem.',
//     'Mech.',
//     'Med.',
//     'Medit.',
//     'Mtg.',
//     'Mem.',
//     'Merch.',
//     'Merc.',
//     'Metallif.',
//     'Metallogr.',
//     'Metall.',
//     'Metamorph.',
//     'metaphor.',
//     'Metaph.',
//     'Meteorol.',
//     'Meth.',
//     'metr. gr.',
//     'Metrop.',
//     'Mex.',
//     'Mich.',
//     'Microbiol.',
//     'Microsc.',
//     'midl.',
//     'Mil.',
//     'Milit.',
//     'Min.',
//     'Mineral.',
//     'Misc.',
//     'Miscell.',
//     'mispr.',
//     'mod.',
//     'Monum.',
//     'Morphol.',
//     'Mt.',
//     'Mts.',
//     'Munic.',
//     'Munif.',
//     'Munim.',
//     'Mus.',
//     'Myst.',
//     'Myth.',
//     'Mythol.',
//     'Narr.',
//     'Narrat.',
//     'Nat.',
//     'Nat. Hist.',
//     'Nat. Philos.',
//     'Nat. Sci.',
//     'Naut.',
//     'Nav.',
//     'Navig.',
//     'Neighb.',
//     'Nerv.',
//     'Neurol.',
//     'Neurosurg.',
//     'n.',
//     'N.E.D.',
//     'New Hampsh.',
//     'N.S. Wales',
//     'N.S.W.',
//     'N.T.',
//     'N.Y.',
//     'N.Z.',
//     'Newc.',
//     'Newspr.',
//     'nom.',
//     'nonce-wd.',
//     'Non-conf.',
//     'Nonconf.',
//     'Norf.',
//     'N. Afr.',
//     'N. Amer.',
//     'N. Carolina',
//     'N. Dakota',
//     'Northamptonsh.',
//     'Northants.',
//     'N.E.',
//     'north.',
//     'N. Irel.',
//     'N. Ir.',
//     'Northumbld.',
//     'Northumb.',
//     'Northumbr.',
//     'N.W.',
//     'Norw.',
//     'Norweg.',
//     'Notts.',
//     'ns.',
//     'Nov.',
//     'Nucl.',
//     'No.',
//     'Numism.',
//     'Obed.',
//     'Obj.',
//     'obl.',
//     'Observ.',
//     'obs.',
//     'Obstetr. Med.',
//     'Obstet.',
//     'Obstetr.',
//     'Occas.',
//     'Occup.',
//     'Occurr.',
//     'Oceanogr.',
//     'Oct.',
//     'Offic.',
//     'Off.',
//     'Okla.',
//     'O.T.',
//     'Ont.',
//     'Ophthalm.',
//     'Ophthalmol.',
//     'opp.',
//     'Oppress.',
//     'Opt.',
//     'Orac.',
//     'Ord.',
//     'Org.',
//     'Organ. Chem.',
//     'Org. Chem.',
//     'orig.',
//     'Orkn.',
//     'Ornith.',
//     'Ornithol.',
//     'Orthogr.',
//     'Outl.',
//     'Oxf.',
//     'O.E.D.',
//     'Oxfordsh.',
//     'Oxon.',
//     'p.',
//     'Palaeobot.',
//     'Palaeogr.',
//     'Palaeont.',
//     'Palaeontol.',
//     'Paraphr.',
//     'Parasitol.',
//     'Parl.',
//     'Parnass.',
//     'Pt.',
//     'ppl.',
//     'ppl. a.',
//     'ppl. adj.',
//     'ppl. adjs.',
//     'pple.',
//     'pples.',
//     'pa. pple.',
//     'pass.',
//     'pa.',
//     'pa. t.',
//     'Path.',
//     'Pathol.',
//     'Peculat.',
//     'Penins.',
//     'perf.',
//     'pf.',
//     'perh.',
//     'Periodontol.',
//     'Persec.',
//     'Pers.',
//     'personif.',
//     'Perthsh.',
//     'Petrogr.',
//     'Petrol.',
//     'Pharmaceut.',
//     'Pharm.',
//     'Pharmacol.',
//     'Philad.',
//     'Philol.',
//     'Philos.',
//     'Phoen.',
//     'phonet.',
//     'Phonol.',
//     'Photog.',
//     'Photogr.',
//     'phr.',
//     'Phrenol.',
//     'Physical Chem.',
//     'Physical Geogr.',
//     'Physiogr.',
//     'Phys.',
//     'Physiol.',
//     'Pict.',
//     'pl.',
//     'plur.',
//     'poet.',
//     'Pol. Econ.',
//     'Pol.',
//     'Polit.',
//     'Polytechn.',
//     'Pop.',
//     'Porc.',
//     'Port.',
//     'poss.',
//     'Posth.',
//     'Postm.',
//     'Pott.',
//     'Pract.',
//     'prec.',
//     'pred.',
//     'predic.',
//     'Predict.',
//     'Pref.',
//     'Preh.',
//     'Prehist.',
//     'prep.',
//     'Prerog.',
//     'Presb.',
//     'pr.',
//     'pres.',
//     'pres. pple.',
//     'pr. pple.',
//     'Preserv.',
//     'Prim.',
//     'Princ.',
//     'Print.',
//     'priv.',
//     'Probab.',
//     'prob.',
//     'Probl.',
//     'Proc.',
//     'Prod.',
//     'Prol.',
//     'pron.',
//     'pronunc.',
//     'prop.',
//     'propr.',
//     'Pros.',
//     'Provid.',
//     'Provinc.',
//     'Provis.',
//     'pseudo-arch.',
//     'pseudo-dial.',
//     'pseudo-Sc.',
//     'Psychoanal.',
//     'Psychoanalyt.',
//     'Psych.',
//     'Psychol.',
//     'Psychopathol.',
//     'Publ.',
//     'P. R.',
//     'Purg.',
//     'Quantum Mech.',
//     'Q.',
//     'Q. Eliz.',
//     'Queen’s Bench Div.',
//     'Qld.',
//     'q.v.',
//     'quot.',
//     'quots.',
//     'Radiol.',
//     'Reas.',
//     'Reb.',
//     'Rebell.',
//     'Reclam.',
//     'Recoll.',
//     'Rec.',
//     'Redempt.',
//     'redupl.',
//     'refash.',
//     'Ref.',
//     'Refl.',
//     'Refus.',
//     'Refut.',
//     'Regic.',
//     'Reg.',
//     'Regist.',
//     'Regr.',
//     'rel.',
//     'Relig.',
//     'Reminisc.',
//     'Remonstr.',
//     'Renfrewsh.',
//     'Rep.',
//     'Rept.',
//     'repr.',
//     'Reprod.',
//     'Repub.',
//     'Res.',
//     'Resid.',
//     'Retrosp.',
//     'Ret.',
//     'Revol.',
//     'Rhet.',
//     'Rhode Isl.',
//     'Rich.',
//     'Rom. Antiq.',
//     'R.C. Church',
//     'R.C.',
//     'Ross-sh.',
//     'Roxb.',
//     'R.',
//     'Roy.',
//     'R.A.F.',
//     'R.N.',
//     'Rudim.',
//     'Russ.',
//     'St.',
//     'SS.',
//     'Sask.',
//     'Sat.',
//     'Sax.',
//     'Scand.',
//     'Sch.',
//     'Sci.',
//     'sc.',
//     'Scotl.',
//     'Scot.',
//     'S.T.S.',
//     'Script.',
//     'Sculpt.',
//     'Seismol.',
//     'Sel. comm.',
//     'Sel.',
//     'Select.',
//     'Sept.',
//     'LXX',
//     'Ser.',
//     'Serm.',
//     'Sess.',
//     'Settlem.',
//     'Sev.',
//     'Shakes.',
//     'Shaks.',
//     'Sheph.',
//     'Shetl.',
//     'Shropsh.',
//     'sing.',
//     'Soc.',
//     'Sociol.',
//     'Som.',
//     'Sonn.',
//     's.',
//     'S. Afr.',
//     'S. Carolina',
//     'S. Dakota',
//     'S.E.',
//     'south.',
//     'S.W.',
//     'Span.',
//     'Spec.',
//     'Specif.',
//     'Specim.',
//     'Spectrosc.',
//     'sp.',
//     'Staff.',
//     'Stafford.',
//     'Staffordsh.',
//     'Staffs.',
//     'Stand.',
//     'Stat.',
//     'Statist.',
//     'Stock Exch.',
//     'Stratigr.',
//     'str.',
//     'Struct.',
//     'Stud.',
//     's.v.',
//     'subj.',
//     'subjunct.',
//     'subord.',
//     'subord. cl.',
//     'Subscr.',
//     'Subscript.',
//     'subseq.',
//     'subst.',
//     'suff.',
//     'superl.',
//     'Suppl.',
//     'Supplic.',
//     'Suppress.',
//     'Surg.',
//     'Surv.',
//     'syll.',
//     'Symmetr.',
//     'Symp.',
//     'Syst.',
//     'Taxon.',
//     'techn.',
//     'Technol.',
//     'Telecomm.',
//     'Tel.',
//     'Telegr.',
//     'Teleph.',
//     't.',
//     'Teratol.',
//     'Terminol.',
//     'Terrestr.',
//     'Test.',
//     'Textbk.',
//     'Theat.',
//     'Theatr.',
//     'Theol.',
//     'Theoret.',
//     'Thermonucl.',
//     'Thes.',
//     'Topogr.',
//     'Trad.',
//     'Trag.',
//     'Trans.',
//     'transf.',
//     'Transl.',
//     'tr.',
//     'Transubstant.',
//     'Trav.',
//     'Treas.',
//     'Treat.',
//     'Treatm.',
//     'Trib.',
//     'Trig.',
//     'Trigonom.',
//     'Trop.',
//     'Troub.',
//     'Troubl.',
//     'Typog.',
//     'Typogr.',
//     'ult.',
//     'U.S.S.R.',
//     'U.K.',
//     'U.S.',
//     'U.S.A.F.',
//     'Univ.',
//     'unkn.',
//     'Unnat.',
//     'Unoffic.',
//     'unstr.',
//     'Urin.',
//     'usu.',
//     'Utilit.',
//     'Vac.',
//     'Valedict.',
//     'var.',
//     'v.r.',
//     'v.rr.',
//     'varr.',
//     'vars.',
//     'Veg.',
//     'Veg. Phys.',
//     'Veg. Physiol.',
//     'Venet.',
//     'v.',
//     'vb.',
//     'vbl.',
//     'vbl.n.',
//     'vbl. ns.',
//     'vbs.',
//     'Vertebr.',
//     'Vet. Med.',
//     'Vet. Path.',
//     'Vet. Sci.',
//     'Vet. Surg.',
//     'Vet.',
//     'Vic.',
//     'Vict.',
//     'viz.',
//     'Vind.',
//     'Vindic.',
//     'Virg.',
//     'Va.',
//     'Virol.',
//     'Voc.',
//     'Vocab.',
//     'Vol.',
//     'Vols.',
//     'Voy.',
//     'Vulg.',
//     'Warwicksh.',
//     'wk.',
//     'Wkly.',
//     'w.',
//     'W. Afr.',
//     'W. Indies',
//     'W. Ind.',
//     'W. Va.',
//     'west.',
//     'Westm.',
//     'Westmld.',
//     'Westmorld.',
//     'Westmrld.',
//     'Will.',
//     'Wilts.',
//     'Wiltsh.',
//     'Wis.',
//     'Wonderf.',
//     'Worc.',
//     'Worcestersh.',
//     'Worcs.',
//     'wd.',
//     'Wks.',
//     'Writ.',
//     'Yr.',
//     'Yearbk.',
//     'Yrs.',
//     'Yorks.',
//     'Yorksh.',
//     'Yng.',
//     'Zeitschr.',
//     'Zoogeogr.',
//     'Zool.',
//   ];

//   static const noPlurals = [
//     'accommodation',
//     'advice',
//     'aggression',
//     'air',
//     'aircraft',
//     'applause',
//     'art',
//     'assistance',
//     'attention',
//     'baggage',
//     'luggage',
//     'beauty',
//     'beef',
//     'billiards',
//     'bravery',
//     'bread',
//     'business',
//     'butter',
//     'cheese',
//     'chess',
//     'courage',
//     'curiosity',
//     'currency',
//     'deer',
//     'dirt',
//     'dust',
//     'education',
//     'entertainment',
//     'equipment',
//     'faith',
//     'fish',
//     'flour',
//     'freedom',
//     'fruit',
//     'fun',
//     'furniture',
//     'garbage',
//     'rubbish',
//     'litter',
//     'gas',
//     'petrol',
//     'grass',
//     'grief',
//     'guilt',
//     'hair',
//     'health',
//     'heat',
//     'height',
//     'help',
//     'homework',
//     'honey',
//     'housework',
//     'humour',
//     'hunger',
//     'information',
//     'jam',
//     'judo',
//     'yoga',
//     'knowledge',
//     'land',
//     'laughter',
//     'lightning',
//     'literature',
//     'love',
//     'mail',
//     'mathematics',
//     'measles',
//     'milk',
//     'mud',
//     'nature',
//     'news',
//     'nutrition',
//     'obesity',
//     'offspring',
//     'oil',
//     'paper',
//     'pasta',
//     'physics',
//     'poetry',
//     'pork',
//     'rain',
//     'rice',
//     'salmon',
//     'salt',
//     'satisfaction',
//     'sheep',
//     'strength',
//     'sugar',
//     'sunshine',
//     'swine',
//     'tea',
//     'thirst',
//     'time',
//     'traffic',
//     'transportation',
//     'travel',
//     'underwear',
//     'vision',
//     'water',
//     'weight',
//     'wine',
//     'wisdom',
//     'bison',
//     'buffalo',
//     'carp',
//     'cod',
//     'metadata',
//     'data',
//     'deer',
//     'fish',
//     'kakapo',
//     'neat',
//     'pike',
//     'salmon',
//     'sheep',
//     'shrimp',
//     'squid',
//     'trout',
//     'elk',
//     'moose',
//     'kudo',
//     'oryx',
//     'springbok',
//     'nyala',
//     'duiker'
//   ];

//   static const uniquePlurals = {
//     'ox': 'oxen',
//     'child': 'children',
//     'brother': 'brethren',
//     'foot': 'feet',
//     'goose': 'geese',
//     'louse': 'lice',
//     'dormouse': 'dormice',
//     'man': 'men',
//     'mouse': 'mice',
//     'tooth': 'teeth',
//     'woman': 'women',
//     'person': 'people',
//     'die': 'dice',
//     'penny': 'pence',
//     'alkali': 'alkalies'
//   };

//   static const sPluralExceptions = [
//     'canto',
//     'hetero',
//     'photo',
//     'zero',
//     'piano',
//     'portico',
//     'pro',
//     'quarto',
//     'kimono'
//   ];

//   static const vowels = ['a', 'e', 'i', 'o', 'u'];

//   static const consonants = [
//     'b',
//     'c',
//     'd',
//     'f',
//     'g',
//     'h',
//     'j',
//     'k',
//     'l',
//     'm',
//     'n',
//     'p',
//     'q',
//     'r',
//     's',
//     't',
//     'v',
//     'w',
//     'x',
//     'y',
//     'z'
//   ];
// }

// // extension EnglishExtension on String {
// //   String get plural {
// //     final retVal = _singleCharacter ??
// //         _noPlural ??
// //         _uniquePlural ??
// //         _endsWith ??
// //         '${this}s';
// //     return isUpperCase ? retVal.toUpperCase() : retVal;
// //   }

// //   String? get _noPlural {
// //     if (English.noPlurals.contains(toLowerCase())) {
// //       return this;
// //     }
// //     for (final ends in English.noPlurals) {
// //       // print(snakeCase);
// //       // print(camelCase);
// //       // print(pascalCase);
// //       // print(titleCase);
// //       if (toLowerCase().endsWith(ends.toLowerCase())) {
// //         if (ends == 'rice' && toLowerCase().endsWith('price')) {
// //           return null;
// //         }
// //         final split = snakeCase.split('_');
// //         var first = substring(0, length - ends.length);
// //         var last = substring(first.length);
// //         if (split.length > 1) {
// //           first = substring(0, length - split.last.length);
// //           last = substring(first.length);
// //         }
// //         if (last.toLowerCase() == ends) {
// //           return '${first.plural}$last';
// //         }
// //         if (ends == 'rice' && toLowerCase().endsWith('price')) {
// //           return null;
// //         }
// //       }
// //     }
// //     return null;
// //   }

// //   String? get _uniquePlural {
// //     final lcase = toLowerCase();
// //     if (English.uniquePlurals.keys.contains(lcase)) {
// //       final val = English.uniquePlurals[lcase] as String;
// //       return isTitleCase
// //           ? val.titleCase
// //           : isUpperCase
// //               ? val.toUpperCase()
// //               : val;
// //     }
// //     for (final ends in English.uniquePlurals.entries) {
// //       if (toLowerCase().endsWith(ends.key.toLowerCase())) {
// //         final first = substring(0, length - ends.key.length);
// //         final last = substring(first.length);
// //         return '$first${last.plural}';
// //       }
// //     }
// //     return null;
// //   }

// //   String? get _singleCharacter {
// //     if (length == 1) {
// //       return "${this}'s";
// //     }
// //     return null;
// //   }

// //   String? get _endsWith {
// //     final lcase = toLowerCase();
// //     final last = lcase.substring(length - 1);
// //     final lastTwo = (length > 1 ? lcase.substring(length - 2) : last);
// //     String? retVal;
// //     if (lastTwo.endsWith('f')) {
// //       retVal = '${substring(0, length - 1)}ves';
// //     } else if (lastTwo.endsWith('fe')) {
// //       retVal = '${substring(0, length - 2)}ves';
// //     } else if (lastTwo.endsWith('ch') ||
// //         lastTwo.endsWith('sh') ||
// //         lastTwo.endsWith('s') ||
// //         lastTwo.endsWith('ss') ||
// //         lastTwo.endsWith('x') ||
// //         lastTwo.endsWith('z')) {
// //       retVal = '${this}es';
// //     } else if (lastTwo.substring(0, 1).isConsonant) {
// //       if (lastTwo.endsWith('y')) {
// //         retVal = '${substring(0, length - 1)}ies';
// //       } else if (lastTwo.endsWith('o') &&
// //           !English.sPluralExceptions.contains(toLowerCase())) {
// //         retVal = '${this}es';
// //       }
// //     }
// //     return retVal;
// //   }
// // }

// // class EnglishRegex implements LocaleRegex {
// //   const EnglishRegex();

// //   /// Does not match characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   static const nonWordChars = r"[^a-zA-Z0-9-¥Œ€@™#-\&_'-]";
// //   @override
// //   final nonWordChar = nonWordChars;

// //   static RegExp get nonWordCharacters => RegExp(nonWordChars);

// //   static RegExp get words => RegExp(word);

// //   static RegExp get wordCharacters => RegExp(wordChars);

// // //    '?([a-zA-Z0-9-¥Œ€@™#-\&_'-]+)'?

// // // ignore: prefer_interpolation_to_compose_strings
// //   static const word = (r"'?(" + wordChars + "+)'?");

// //   /// Matches characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   static const wordChars = r"[a-zA-Z0-9-¥Œ€@™#-\&_'-]";
// //   @override
// //   final wordChar = wordChars;

// //   /// Matches all letters of the alphabet, non-case sensitive.
// //   static const letters = r'[a-zA-z]';
// //   @override
// //   final lettersChar = letters;

// //   /// Matches any character except letters of the alphabet, non-case sensitive.
// //   static const nonLetters = r'[^a-zA-z]';
// //   @override
// //   final nonLettersChar = nonLetters;

// //   /// Matches all numbers
// //   static const numbers = r'[0-9]';
// //   @override
// //   final numbersChar = numbers;

// //   /// Matches any character except numbers 0-9
// //   static const nonNumbers = r'[^0-9]';
// //   @override
// //   final nonNumbersChar = nonNumbers;

// //   /// Matches all letters and numbers.
// //   static const alphaNumeric = r'[a-zA-Z0-9]';
// //   @override
// //   final alphaNumricMatch = alphaNumeric;

// //   /// Matches all charcters except letters and numbers.
// //   static const nonAlphaNumeric = r'[^a-zA-Z0-9]';
// //   @override
// //   final nonAlphaNumricMatch = nonAlphaNumeric;
// // }

// // class EuroRegex implements LocaleRegex {
// //   const EuroRegex();

// //   /// Does not match characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   static const nonWord = r"[^a-zA-z0-9À-ÖØ-öø-ÿž¢-¥ŽŸœŒŠ‰€@™š#-\&_'-]";
// //   @override
// //   final nonWordChar = nonWord;

// //   /// Matches characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   static const word = r"[a-zA-z0-9À-ÖØ-öø-ÿž¢-¥ŽŸœŒŠ‰€@™š#-\&_'-]";
// //   @override
// //   final wordChar = word;

// //   /// Matches all letters of the alphabet, non-case sensitive.
// //   static const letters = r'[a-zA-z]';
// //   @override
// //   final lettersChar = letters;

// //   /// Matches any character except letters of the alphabet, non-case sensitive.
// //   static const nonLetters = r'[^a-zA-z]';
// //   @override
// //   final nonLettersChar = nonLetters;

// //   /// Matches all numbers
// //   static const numbers = r'[0-9]';
// //   @override
// //   final numbersChar = numbers;

// //   /// Matches any character except numbers 0-9
// //   static const nonNumbers = r'[^0-9]';
// //   @override
// //   final nonNumbersChar = nonNumbers;

// //   /// Matches all letters and numbers.
// //   static const alphaNumeric = r'[a-zA-Z0-9]';
// //   @override
// //   final alphaNumricMatch = alphaNumeric;

// //   /// Matches all charcters except letters and numbers.
// //   static const nonAlphaNumeric = r'[^a-zA-Z0-9]';
// //   @override
// //   final nonAlphaNumricMatch = nonAlphaNumeric;
// // }

// // abstract class LocaleRegex {
// //   //
// //   /// Does not match characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   String get nonWordChar;

// //   /// Matches characters used to write words, including:
// //   ///   - numbers 0-9;
// //   ///   - letters a-z;
// //   ///   - letters A-Z;
// //   ///   - ampersand, apostrophe, underscore and hyhpen ("&", "'", "_", "-")
// //   String get wordChar;

// //   /// Matches all letters of the alphabet, non-case sensitive.
// //   String get lettersChar;

// //   /// Matches any character except letters of the alphabet, non-case sensitive.
// //   String get nonLettersChar;

// //   /// Matches all numbers
// //   String get numbersChar;

// //   /// Matches any character except numbers 0-9
// //   String get nonNumbersChar;

// //   /// Matches all letters and numbers.
// //   String get alphaNumricMatch;

// //   /// Matches all charcters except letters and numbers.
// //   String get nonAlphaNumricMatch;
// // }
